### ISSUE TITLE
where is the ./bin

### ISSUE THREAD

**Issue by Midolii** [3Shain/yet-another-anime-game-launcher#1]
how to get neutralino.js?

**Comment by 3Shain** [comment]
run `pnpm exec neu update`

**Comment by Midolii** [comment]
> run `pnpm exec neu update`

no neutralino.js, only some binary and one .dll

**Comment by 3Shain** [comment]
> > run `pnpm exec neu update`
> 
> no neutralino.js, only some binary and one .dll

should be already at `/dist/neutralino.js` after that command. Copy it to `/bin/neutralino.js` (I see there is a problem with `pnpm start` script, will fix it later
