### ISSUE TITLE
not working on 2021 14" M1 Pro

### ISSUE THREAD

**Issue by Stooovie** [3Shain/yet-another-anime-game-launcher#10]
"Game is running" but no screen gets spawned. It did get spawned before, but it was empty (black) indefinitely. 

Ventura 13.3

Here's the log, this seems sus:

`27531.726:0108:err:module:import_dll Loading library winspool.drv (which is needed by L"C:\\windows\\system32\\wbem\\wbemprox.dll") failed (error c0000005).
27531.727:0108:err:ole:apartment_add_dll couldn't load in-process dll L"C:\\windows\\system32\\wbem\\wbemprox.dll"
27531.727:0108:err:ole:com_get_class_object no class object {4590f811-1d3a-11d0-891f-00aa004b2e24} could be created for context 0x1`

entire log:
https://transfer.sh/7X2OFi/game_1680019971452.log

**Comment by 3Shain** [comment]
Have you tried switching between different wine distributions?
(And maybe this is related: it's reported from many 13.3 users that crossover failed to work. This project is using a FOSS version of crossover which is likely to get affected)

**Comment by Stooovie** [comment]
I have, yes. No success so far. It's probably the Ventura update thing.

**Comment by dummyaja** [comment]
@Stooovie 
please check solution in this issue #17 
https://github.com/3Shain/yet-another-anime-game-launcher/issues/17

**Comment by 3Shain** [comment]
Have you tested `unstable-gi-wine-1.2`? This might solve your problem.
