### ISSUE TITLE
"Not enough freespace" when I have enough freespace

### ISSUE THREAD

**Issue by Clyde-Timonera** [3Shain/yet-another-anime-game-launcher#100]
<img width="1276" alt="Screenshot 2023-05-12 at 6 38 29 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/78290310/1af06516-f6cd-4b07-8e58-aa9bfba8c716">
<img width="476" alt="Screenshot 2023-05-12 at 6 40 13 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/78290310/dfe3c144-a487-4f06-b4c6-0d67bb84742b">

**Comment by Clyde-Timonera** [comment]
The Anime Game asks it even after system restart.

**Comment by 3Shain** [comment]
https://github.com/3Shain/yet-another-anime-game-launcher/issues/60#issuecomment-1498423295

if you have Time Machine you may have to disable it.

**Comment by Shahbod123** [comment]
Hi I disabled time machine but stil have the same problem although I have storage

**Comment by 3Shain** [comment]
> Hi I disabled time machine but stil have the same problem although I have storage

https://apple.stackexchange.com/questions/375960/what-is-a-good-replacement-for-the-df-command-that-is-broken-on-macos-mojave

**Comment by FireNuke** [comment]
nothing works please fix it because I have space and cannot even download it.

**Comment by FireNuke** [comment]
U closed thread and didn't even asked if it worked great dev.
