### ISSUE TITLE
Code:-9006 Failed to download resource files or network error. Please Try again.

### ISSUE THREAD

**Issue by Xanks17** [3Shain/yet-another-anime-game-launcher#103]
**Describe the bug**
Hi, I can't proceed to play, does anyone encounter this? let me know, thanks.

**Screenshots**
If applicable, add screenshots to help explain your pro
<img width="2240" alt="Screenshot 2023-05-17 at 9 18 54 AM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/133829760/55ceab54-1c06-4f50-9e5c-6587f022cc8b">
blem.

**System Information (please complete the following information):**
 - macOS: [e.g. 13.1 Ventura]
 - Device: [e.g. MacbookPro 16inch 2019 ]
 - CPU: [e.g. Apple M1, Intel i7 9750H ]
 - Dedicated GPU (if any): [e.g.  AMD Radeon Pro 5300M ]
 - RAM: [e.g. 16G ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by 3Shain** [comment]
why not just search for some closed issues which has exactly the same problem you've posted?
