### ISSUE TITLE
Anime Game stuck in an awkward position and no way to set to fullscreen.

### ISSUE THREAD

**Issue by Clyde-Timonera** [3Shain/yet-another-anime-game-launcher#104]
<img width="1679" alt="Screenshot 2023-05-19 at 9 12 19 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/78290310/422ce119-6061-4fbf-a9bb-d883980b39c7">

**Comment by 3Shain** [comment]
option + enter 
or
command + enter
to switch to fullscreen
----
seriously how is this worth filing an issue? you can just enter the game and change the in-gaming setting. it's so strange that i think you are abusing github issues.

**Comment by Clyde-Timonera** [comment]
Well the in game settings would all say "windowed" so I'd thought of filing a report, sorry.
