### ISSUE TITLE
Version 3.7 support

### ISSUE THREAD

**Issue by ksckaan1** [3Shain/yet-another-anime-game-launcher#105]
**Describe the bug**
After update Genshin impact to 3.7, can not open game over launcher and shows error

**Screenshots**
![Screenshot 2023-05-24 at 13 09 46](https://github.com/3Shain/yet-another-anime-game-launcher/assets/33625775/4bda86b8-b0f4-4d1e-a007-431be84272f7)

**System Information (please complete the following information):**
 - macOS: 13.3 Ventura
 - Device: Mac Mini 2020
 - CPU: Apple M1
 - Dedicated GPU (if any): Apple M1
 - RAM:  16G

**Comment by 3Shain** [comment]
Update will arrive 3 days later (27th)

**Comment by ksckaan1** [comment]
ok. Thank you!
