### ISSUE TITLE
Download failure

### ISSUE THREAD

**Issue by dancju** [3Shain/yet-another-anime-game-launcher#108]
**Describe the bug**
First run of international version. Clicked "Install Game" then this pop up instantly.

**Screenshots**
<img width="1289" alt="image" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/3108734/c56bdc6b-9143-47aa-9c8c-df8d8f59dbff">

**System Information (please complete the following information):**
 - macOS: Ventura 13.3.1
 - Device: MacbookPro, 16-inch, 2021
 - CPU:  Apple M1 Pro
 - RAM: 16Gb

**Comment by zitongzhan** [comment]
https://github.com/3Shain/yet-another-anime-game-launcher/issues/107
