### ISSUE TITLE
Download failure

### ISSUE THREAD

**Issue by Sh1vrajsinh** [3Shain/yet-another-anime-game-launcher#109]
Is this happening because of the new 3.7 version being unsupported or is it something else?

<img width="1290" alt="SCR-20230526-nxqs" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/130572542/2beb01ad-9e3d-460b-bcd8-7737e6619ce4">

 - macOS: Ventura 13.3.1 
 - Device: Late 2020 Macbook Air
 - CPU: Apple M1
 - Dedicated GPU : None
 - RAM: 8GB

I have no clue why this might be happening and would really appreciate some help. Even if that help might just be telling me if I have to wait for the new version of yaagl.

**Comment by 3Shain** [comment]
#107

**Comment by Sh1vrajsinh** [comment]
> #107

Thank you!
