### ISSUE TITLE
Can't connect in the game

### ISSUE THREAD

**Issue by Sghas** [3Shain/yet-another-anime-game-launcher#11]
I can't do the captcha on my mac there is white blank box and I connot do nothing

**Comment by 3Shain** [comment]
Have you tried to just press the enter key?

**Comment by Sghas** [comment]
Yes I press the enter key and nothing is append

**Comment by Sghas** [comment]
<img width="1132" alt="Capture d’écran 2023-03-30 à 19 28 08" src="https://user-images.githubusercontent.com/129228910/229227245-1a070090-e5f6-4cbf-90d5-c01e136e573a.png">
