### ISSUE TITLE
Today, (may 27th) was the release of version 3.7 on yaagl but when I click on launch game it still says it doesn't support it

### ISSUE THREAD

**Issue by Eimikocanon** [3Shain/yet-another-anime-game-launcher#112]
**Is your feature request related to a problem? Please describe.**
I dont know[...]

**Describe the solution you'd like**
The solution I'd like is a way to fix this or if I did anything wrong

**Describe alternatives you've considered**
Checked the game file integrity

**Additional context**
when I click launch game it says "The launcher currently doesn't support version 3.7.0 currently, please wait for further updates".

**Comment by 3Shain** [comment]
https://github.com/3Shain/yet-another-anime-game-launcher/releases/tag/0.1.0-rc.1 you have to manually update

**Comment by Eimikocanon** [comment]
> https://github.com/3Shain/yet-another-anime-game-launcher/releases/tag/0.1.0-rc.1 you have to manually update

how do I manually update?
