### ISSUE TITLE
Error: At least 117.6GiB (126.3GB) of freespace is required on your disk.

### ISSUE THREAD

**Issue by a-singh09** [3Shain/yet-another-anime-game-launcher#114]
**Describe the bug**
Showing the error "At least 117.6GiB (126.3GB) of freespace is required on your disk." while downlloading the game. I have about 135gb of free disk space.

**Screenshots**
<img width="433" alt="image" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/96711588/87c6301c-ce60-44c3-983b-533d4eadb560">

**System Information:**
 - macOS: 13.3.1(a) Ventura
 - Device: MacbookAir M1
 - CPU: Apple M1
 - RAM: *8GB

**Additional context**
The first time i downloaded the launcher, it started downloading but after downloading about 20 gb, it stopped downloading. I restarted but of no use. I reinstalled yaagl in a new folder and clicked on install game button but now it gives me this error.

**Comment by 3Shain** [comment]
#100 please do some research

**Comment by imfabianc** [comment]
I also have the same problem, could someone solve it?

**Comment by FireNuke** [comment]
Doesn't even work bruh tell us real solution

> #100 please do some research
