### ISSUE TITLE
Error When Installing Genshin

### ISSUE THREAD

**Issue by BentoMic** [3Shain/yet-another-anime-game-launcher#115]
After choosing my file, Fatal error pops up on the Allocating files on disk screen: {"code":1,"message":"No URI to download."}

 - macOS Montery Version 12.5
 - Macbook Air 13 inch 2019
 - Apple M1
 - 8 GB

Please help. Sideloading doesn't work out for me either.

**Comment by 3Shain** [comment]
Update yaagl to latest version.
