### ISSUE TITLE
Make fullscreen stop under the notch

### ISSUE THREAD

**Issue by Jepl4r** [3Shain/yet-another-anime-game-launcher#12]
Can you please make the game window go under the notch when it's set to fullscreen in a future update?

**Comment by 3Shain** [comment]
It needs the support from upstream (crossover) so I can't really help much (also I have no such a device to test against) but [for your reference](https://www.reddit.com/r/macgaming/comments/xv380h/best_way_to_make_crossover_games_avoid_the_notch/)
