### ISSUE TITLE
Stuck on allocating files

### ISSUE THREAD

**Issue by randomarchuser** [3Shain/yet-another-anime-game-launcher#121]
**Describe the bug**
The launcher displays "allocating files" but does not proceed the installation. The progress bar animation plays indefinitely.

**Screenshots**
<img width="1268" alt="Screenshot 2023-06-15 at 12 12 36" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/110524712/af9d82e4-cd42-4a83-b665-0e8f75596ef6">

**System Information (please complete the following information):**
 - macOS: 13.2 Ventura
 - Device: Macbook Air M1 2020
 - CPU: Apple M1
 - Dedicated GPU (if any): M1
 - RAM: 8G

**Additional context**
I'm a bit confused why there is no dependency listed in the README because the program asked me to install aria2 after I ran it. Could there be any more dependencies I need to install?

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 
I'm not sure where this is.

**Comment by randomarchuser** [comment]
Oh, I see now that aria2 is included with the package. For some reason it did not work for me the first time.

**Comment by randomarchuser** [comment]
Yet the issue stays the same.

**Comment by Soliturd** [comment]
How did you fix this glitch? I cannot open the game right now and have no clue how to fix.
