### ISSUE TITLE
Stuck at allocating files

### ISSUE THREAD

**Issue by randomarchuser** [3Shain/yet-another-anime-game-launcher#124]
**Describe the bug**
The launcher hangs at allocating files. It's not frozen, but just won't move to the next stage.

**Screenshots**
<img width="1280" alt="Screenshot 2023-06-19 at 15 53 19" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/110524712/58c36233-ceb2-497a-b5a0-713b71d18644">

**System Information (please complete the following information):**
 - macOS: 13.4 Ventura
 - Device: Macbook Air M1 2020
 - CPU: M1
 - RAM: 8G

**Additional context**
I'm not sure if SIP needs to be disabled because mine is enabled. Also I installed a bunch of brew packages and I don't know if that affects the launcher.

**Logs (if any)**
[neutralinojs.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11788899/neutralinojs.log)

**Comment by randomarchuser** [comment]
Solved. The server was blocked by my network and using a VPN fixes it.

**Comment by ZoZeck** [comment]
I was always using VPN but when I finally turned it off it start downloading
