### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by nhatsun** [3Shain/yet-another-anime-game-launcher#128]
**Describe the bug**
The game randomly crashes when teleport
**Screenshots**

**System Information (please complete the following information):**
 - macOS: e.g. 13.4.1 Ventura
 - Device: MacbookAir 13inch Late 2020
 - CPU: Apple M1
 - RAM: 8G

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

Thanks for seeing this post

**Comment by nhatsun** [comment]
And recently, i noticed huge log file in the game, like more than 50gb, can you show me how to fix that ?

**Comment by 3Shain** [comment]
Hmmm playcover is a better way for you.
Log files can be freely deleted.

**Comment by nhatsun** [comment]
thanks very much, just worrying when the log go crazy, macos cant run anymore
