### ISSUE TITLE
Doesn't run on 3.8.0

### ISSUE THREAD

**Issue by ymatuhin** [3Shain/yet-another-anime-game-launcher#129]
<img width="532" alt="Screenshot 2023-07-05 at 13 28 10" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/3757971/bd51d4d7-ca95-430d-8e09-22572842a21d">

**Comment by Jaypilot** [comment]
I think after 4-6 days the new version is released, for now completely uninstall this launcher and check this github every day to see if the new version releases. To uninstall move to app to the bin and delete this folder and its contents : ~/Library/Application Support/Yaagl or ~/Library/Application Support/Yaagl OS if you are using oversea version.

**Comment by morivardo** [comment]
From the Discord server: to play version 3.8.0 'you can actually tick "Turn Off AC Patch" in settings and it seems to just work'

**Comment by ymatuhin** [comment]
> From the Discord server: to play version 3.8.0 'you can actually tick "Turn Off AC Patch" in settings and it seems to just work'

Thanks, I'll try it <3

**Comment by morivardo** [comment]
No problem, I freaked out too :)
