### ISSUE TITLE
3.8 is not working pls look into it

### ISSUE THREAD

**Issue by Nozarashi69** [3Shain/yet-another-anime-game-launcher#130]
**Describe the bug**

**Screenshots**

**System Information (please complete the following information):**
 - macOS: [e.g. 13.1 Ventura]
 - Device: [e.g. MacbookPro 16inch 2019 ]
 - CPU: [e.g. Apple M1, Intel i7 9750H ]
 - Dedicated GPU (if any): [e.g.  AMD Radeon Pro 5300M ]
 - RAM: [e.g. 16G ]

**Additional context**

**Logs (if any)**
<img width="1440" alt="Screenshot 2023-07-05 at 7 56 17 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/138692582/de1dc913-00a4-4422-9b20-9c47679b229b">

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by rvin05** [comment]
hi i dont really understand what the previous comment means, i have the same problem but already have the neutralinojs.log file in my yaagl data directory. can someone give more detailed instructions

**Comment by xuhao1** [comment]
Game porting tool works great to me

**Comment by Nozarashi69** [comment]
> Game porting tool works great to me

but is 3.8 working for you??

**Comment by morivardo** [comment]
From the Discord server: 'you can actually tick "Turn Off AC Patch" in settings and it seems to just work'

**Comment by ajsid09** [comment]
> From the Discord server: to play version 3.8.0 'you can actually tick "Turn Off AC Patch" in settings and it seems to just work'

hey, I have "turned off AC Patch" but When I launch the game it does not work I think there is a problem with my Terminal

**Comment by morivardo** [comment]
What do you mean by "doesn't work"? Is there any error message or does it just not start?

Maybe you can try uninstalling the launcher (not the game files) and reinstalling it

**Comment by ajsid09** [comment]
Currently, in GI I am doing Tenari quest and after talking to npc it just
went black screen and does not respond. And how to reinstall Launcher
without deleting entire files

I will send you an image as well
