### ISSUE TITLE
3.8 is not working

### ISSUE THREAD

**Issue by sevu17** [3Shain/yet-another-anime-game-launcher#131]
**Describe the bug**

**Screenshots**

**System Information (please complete the following information):**
 - macOS: [e.g. 13.1 Ventura]
 - Device: [e.g. MacbookPro 16inch 2019 ]
 - CPU: [e.g. Apple M1, Intel i7 9750H ]
 - Dedicated GPU (if any): [e.g.  AMD Radeon Pro 5300M ]
 - RAM: [e.g. 16G ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by morivardo** [comment]
From the Discord server: "you can actually tick "Turn Off AC Patch" in settings and it seems to just work"
