### ISSUE TITLE
Blank Captcha

### ISSUE THREAD

**Issue by RinRanRun** [3Shain/yet-another-anime-game-launcher#133]
**Describe the bug**
Whenever I click "Start Game" the captcha that would normally be the sliding puzzle is blank.

**Screenshots**
<img width="1512" alt="Screenshot 2023-07-08 at 9 49 16 AM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/138994185/c1a8d296-dac8-4b01-bbfa-472369d5a915">

**System Information (please complete the following information):**
 - macOS: [e.g. 13.0.1 Ventura]
 - Device: [e.g. MacbookPro 14 inch 2022 ]
 - CPU: [e.g. Apple M1, Intel i7 9750H ] (don't know)
 - Dedicated GPU (if any): [e.g.  AMD Radeon Pro 5300M ] (don't know)
 - RAM: [e.g. 16G ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by 3Shain** [comment]
Known issue. Not fixable yet.

**Comment by RinRanRun** [comment]
Aw, dangit, thanks.

**Comment by RinRanRun** [comment]
NTVoid, what I did was I kept clicking and dragging about in the middle of the blank captcha. Eventually, I clicked the slide puzzle, it appeared, and I was able to complete it and log in. I’m not sure if this will work for everyone, but just keep trying and maybe it will work like it did for me. Good luck!

**Comment by RinRanRun** [comment]
Exactly, if I remember correctly, the part where you click to slide the puzzle was a little above the middle point. I could be wrong, but it should generally be in that area. Make sure you drag you cursor after clicking or it won’t work.

**Comment by RinRanRun** [comment]
I’m sorry, I hope it works tomorrow.

**Comment by RinRanRun** [comment]
Yay! I’m glad you found the solution to the problem! Have lots of fun!
