### ISSUE TITLE
Bugged title screen & crashes upon loading

### ISSUE THREAD

**Issue by SimplySora** [3Shain/yet-another-anime-game-launcher#134]
Whenever I open the anime game, and get to the point of the door opening, the graphics bug out, and when I click to continue, it goes through the normal loading process but crashes just before it finishes and loads the actual game.

![Screenshot 2023-07-08 at 2 13 40 PM](https://github.com/3Shain/yet-another-anime-game-launcher/assets/129561051/b7ea85b3-00b8-482f-a7c8-83f8e789bebd)

 - macOS: 13.4.1 Ventura
 - Device: Mac Studio
 - CPU: M1 Max
 - RAM: 64GB

I started having this problem with the last major update to the launcher itself during 3.7. I didn't change any game settings, or even update my Mac at the time. Just all of a sudden stopped working.

[game_1688843070366.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11992281/game_1688843070366.log)

**Comment by SimplySora** [comment]
Tried verifying file integrity and changing wine versions, doesn't fix it.

**Comment by SimplySora** [comment]
Still not sure what the issue was, but reinstalling the whole thing fixed it.

**Comment by ajsid09** [comment]
hey, the anime game  When I start to play a quest it runs for a few minutes but after that shows a black screen
