### ISSUE TITLE
Apple M1 Installer not working

### ISSUE THREAD

**Issue by VoidEUW** [3Shain/yet-another-anime-game-launcher#140]
"Program cannot open" first it said the developer is not verified, so I went around this problem, but still after it doesn't want to start the application. Did I just do a nooby mistake or is there another bigger problem?
<img width="409" alt="Bildschirmfoto 2023-07-12 um 09 11 35" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/113054640/91e5011b-fea8-47dc-8bec-d6a9493a45bb">
this is the error message after trying to launch the installer

 - macOS: [MacOS Sonoma 14.0 Beta]
 - Device: [MacBook Air M1]
 - CPU: [Apple M1]
 - RAM: [16GB]

**Comment by AnonyKVB** [comment]
same im on sonoma beta and it seem to not work for me

**Comment by xissess** [comment]
auf mein Mac mini m1 16gb geht es wunderbar

**Comment by xissess** [comment]
ich habe jetzt 13.5 drauf und habe ein YouTube video dazu als Hilfe benutzt[ ](https://www.youtube.com/watch?v=XplXeOdR98U&t=297s)

**Comment by xissess** [comment]
[(https://www.youtube.com/watch?v=XplXeOdR98U&t=297s)](url)

**Comment by xissess** [comment]
es kann sein das er ein paar mal runterladen muss war bei mir der fall irgendwann hat er es dann geschafft also nicht wundern wenn er lädt und lädt

**Comment by xissess** [comment]
aber du wirst es nicht spielen können da zur Zeit 4.0 noch nicht läuft :-(
