### ISSUE TITLE
4.0 not support

### ISSUE THREAD

**Issue by pastoreli** [3Shain/yet-another-anime-game-launcher#160]
The launcher currently doesn't support version 4.0.0 currently, please wait for further updates
<img width="1276" alt="Screenshot 2023-08-16 at 09 03 24" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/22511012/d6dc2bc8-5288-4e24-81d0-afc9687f0dd7">

**Comment by xissess** [comment]
a few minutes ago i also loaded the update and get the same error message :-(

**Comment by frowing37** [comment]
how to fix that ?

**Comment by pastoreli** [comment]
> perfect :-) this ist a point in a settings enable the checkbox "turn of ac patch"
worked here!!!! thanks!!!

**Comment by Sunny1312** [comment]
thankyou

> try enabling turn of ac patch for now , it will work
