### ISSUE TITLE
keep prompting no enough free space while my mac m1 does have enough free space.

### ISSUE THREAD

**Issue by zhisongliang** [3Shain/yet-another-anime-game-launcher#168]
**Describe the bug**
My mac has almost 200gb free space, but the program keep prompting at least 140gb free space required. 

**Screenshots**
<img width="1061" alt="1" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/87124279/266641c0-ddb1-4a55-9eab-257c2c2ae7fb">
<img width="469" alt="2" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/87124279/92835296-83ec-4852-a7c3-748c9e30384b">

**System Information (please complete the following information):**
 - macOS: 13.0 Ventura
 - Device: MacbookAir 2020 
 - CPU:  Apple M1
 - RAM: 16G

**Comment by JsCoderCole** [comment]
Download CleanMyMac X and remove unwanted files. If you can't afford the program: open settings --> general ---> storage ----> delete whatever you don't need.
