### ISSUE TITLE
Game getting stuck at white screen after Ventura 13.3 Update (FIXED)

### ISSUE THREAD

**Issue by seathasky** [3Shain/yet-another-anime-game-launcher#17]
Launches Hoyoverse logo. Logo fades to white screen and crashes on latest MacOS Ventura 13.3.

Worked fine prior to updating MacOS. Was on 13.2.1 before this.

See short video:

https://user-images.githubusercontent.com/17598024/228405006-68dce0c6-3241-4667-a197-7b53137c5bfd.mov

**My system specs are:**
M2 Mac Mini Pro, 12core cpu 19core gpu, 32gb ram, 1tb SSD

**Comment by ducvd89** [comment]
In my case, the game is not launching at all. 
Macbook Pro 16  2021 M1 Max

**Comment by Stooovie** [comment]
Same

**Comment by sonph63195** [comment]
> In my case, the game is not launching at all. It stuck at Game is running. Nothing happen after that
> Macbook Pro 16 2021 M1 Max
> <img alt="Screenshot 2023-03-29 at 13 43 50" width="1001" src="https://user-images.githubusercontent.com/79311308/228448386-8fb0e5c7-5dd3-4aa8-908b-4327dcd6edda.png">
> <img alt="Screenshot 2023-03-29 at 13 44 58" width="1276" src="https://user-images.githubusercontent.com/79311308/228448524-a6f6d06f-a589-4d85-b279-8f3f88dd99d8.png">

same

**Comment by dummyaja** [comment]
i got same screen look.
this is the last logs
`esync: up and running.
91808.302:002c:err:winediag:getaddrinfo Failed to resolve your host name IP
[2023-03-29 15:14:39.325] MultiThreadStackTrace init success!
GCGMAH active
013c: thread_get_state failed on Apple Silicon - faking zero debug registers
logs/game_1680074073878.log (END)`

**Comment by Vassista** [comment]
So how to run it with wine 8?

**Comment by dummyaja** [comment]
hi @3Shain 
i update to latest release `0.0.34`

still seeing the same error
```Library/Application Support/Yaagl OS
▶ cat GenshinImpact_dxgi.log
info:  Game: GenshinImpact.exe
info:  DXVK: v1.10.3-47-gb144ae28-async (macOS)
info:  Found built-in config:
info:    dxgi.customDeviceDesc = AMD Radeon Pro 5300M
info:  Effective configuration:
info:    dxgi.customDeviceDesc = AMD Radeon Pro 5300M
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module

Library/Application Support/Yaagl OS
▶ cat logs/game_1680151965686.log
esync: up and running.
[2023-03-30 12:52:49.758] MultiThreadStackTrace init success!
GCGMAH active
013c: thread_get_state failed on Apple Silicon - faking zero debug registers```

any info on how to resolve this?

**Comment by seathasky** [comment]
This is resolved here: https://gitlab.winehq.org/wine/wine/-/merge_requests/2329

Also, any devs here are welcome to use the XIV on Mac custom Wine builds, we've had this fixed for 3 weeks. https://github.com/marzent/winecx  @3Shain @Depal1

**Comment by seathasky** [comment]
Those still having issues after updating Ventura to 13.3 can use XIV on Mac wine binaries.
You can find the source here: https://github.com/marzent/winecx

**Download is here:** https://github.com/marzent/winecx/releases/tag/ff-wine-2.4
 
**Instructions:** 

Just replace the "Wine" folder inside the Yaagl OS directory with the one I've provided. 
Click "Open Yaagl Data Directory", delete the Wine folder inside and replace it with the one from the the link i've provided above.
 
![Screenshot 2023-03-30 at 2 19 58 AM](https://user-images.githubusercontent.com/17598024/228747980-43e2c426-2ca0-4097-b948-169e8c84bbc5.png)

![Screenshot 2023-03-30 at 2 26 57 AM](https://user-images.githubusercontent.com/17598024/228748376-dbfdafa8-0901-4468-a6d1-03274c70f052.png)

**Proof it works:**


https://user-images.githubusercontent.com/17598024/228749047-43ca1195-7ef9-4bca-9f96-fa29539297c4.mp4






Hope this helped you guys!

**Comment by dummyaja** [comment]
thx @seathasky for the guide

**Comment by seathasky** [comment]
> thx @seathasky for the guide

You're welcome!

**Comment by dummyaja** [comment]
hi @seathasky 
did u get image is not loading issue in the login page?
how did u resolve it?
![Screenshot 2023-03-30 at 2 38 56 PM](https://user-images.githubusercontent.com/116913/228764677-d34ea66a-cd8f-4315-ac6d-1b3f81fe0754.png)

should i open new issue?

**Comment by dummyaja** [comment]
@seathasky thx again for replying.
will check after all download done

**Comment by yyhhjjj** [comment]
@seathasky The image is abnormal. I don’t know if you have encountered it
![WechatIMG20](https://user-images.githubusercontent.com/116888450/228793589-1222a902-9641-4f68-8c45-f771b8583340.jpeg)

**Comment by 3Shain** [comment]
Seems `unstable-gi-wine-1.2` has solved this.

**Comment by dummyaja** [comment]
thx @3Shain

**Comment by MasqueradeX45** [comment]
> https://github.com/marzent/winecx/releases/tag/ff-wine-2.4

Thanks, changing the wine folder worked. I did need to literally allow every single thing inside the folder inside Mac privacy and security settings though because they couldn't be verified/identified
