### ISSUE TITLE
fps huge drop dragonspine

### ISSUE THREAD

**Issue by yanislouis** [3Shain/yet-another-anime-game-launcher#19]
hello, there is a lag issue that only occurs (as far as i know) at dragonspine and whenever we look at the mountain. My 55 average fps suddently drop to 2 to 7 fps and something like 1-4 fps when im in the mountains i guess it'll be fixed but i report it anyways

https://user-images.githubusercontent.com/44246881/228744878-0fc36168-31ef-4c41-9b7c-4553a52970f4.mp4

**Comment by sonph63195** [comment]
Me same

**Comment by Jepl4r** [comment]
I'm having this problem too. It's more noticeable when using gi-wine 1.2, which is the one I'm using cause I'm on Ventura 13.3 cause gi-wine 1.0 doesn't work.

**Comment by ducvd89** [comment]
need this fix, too. Thanks

**Comment by SimplySora** [comment]
Same, mine isn't as drastic because I'm using 1.0 and on an M1 Max. Drops down to 40-60fps from 100-120

**Comment by 3Shain** [comment]
I won't fix it until I have an Apple Silicon Mac or someone else with professional skills can investigate into this.

**Comment by Jepl4r** [comment]
It's a bug with gi-wine-1.2, when I was playing it with gi-wine-1.0 on MacOS 13.2 it didn't do this. The real problem is that 1.0 doesn't work with MacOS 13.3, so you are stuck with using the unstable 1.2

**Comment by 3Shain** [comment]
> It's a bug with gi-wine-1.2, when I was playing it with gi-wine-1.0 on MacOS 13.2 it didn't do this. The real problem is that 1.0 doesn't work with MacOS 13.3, so you are stuck with using the unstable 1.2

No, this happens _in every wine distributions_.

**Comment by bdshi99** [comment]
This issue not only found in dragonspine and also the desert in Sumeru, FPS dropped to 1-2 after going into the desert.

**Comment by jjarlego** [comment]
Petition to start a contribution for 3Shain to have an Apple Slicon laptop to fix this. Anyone with me?

**Comment by jNaimXIII** [comment]
Yea, the game's unplayable anywhere near the mountain.

**Comment by lavablelavs** [comment]
Couldnt reproduce the same issue, dragonspine works fine for me with barely noticeable fps drops (40-50fps)
Wine Version: gi-wine-1.2
Using Apple M1 13inch Macbook Pro with Ventura 13.3 Dev Beta

**Comment by baysonfox** [comment]
Same as above, probably fixed?
Wine Version: gi-wine-1.2
Apple M2 Pro, Mac14,9 with macOS Ventura 13.3.1 (22E261)

**Comment by jNaimXIII** [comment]
this issue should be marked as resolved now, right? @3Shain

**Comment by Jepl4r** [comment]
The fps goes from 60 to 30 with crossover. I'll try with gi-wine 1.2 to see if it is better, but I think it's playable for now.

**Comment by jNaimXIII** [comment]
> The fps goes from 60 to 30 with crossover. I'll try with gi-wine 1.2 to see if it is better, but I think it's playable for now.

I've been using gl 1.2 and the fps remains a solid 60 even with the high preset. so, yeah it should work for you too.

**Comment by Jepl4r** [comment]
> I've been using gl 1.2 and the fps remains a solid 60 even with the high preset. so, yeah it should work for you too.

Thanks for letting me know :)

**Comment by yanislouis** [comment]
fixed for me too, nice
