### ISSUE TITLE
Fatal launcher error

### ISSUE THREAD

**Issue by MKSlegal** [3Shain/yet-another-anime-game-launcher#191]
yesterday I deleted the launcher and the game folder because I had a bug and I reinstalled it, when the download finished and when I tried to launch the game this error popped out:
<img width="1294" alt="Screenshot 2023-09-24 alle 15 06 32" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/144597714/2f5107c5-839f-4141-b332-5030acb60228">
If someone could hel me please I would appreciate it, heres my neutralinojs log file:
[neutralinojs.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/12708564/neutralinojs.log)

**Comment by TbhGenshinWhy** [comment]
did you find the answer cause i got the same problem

**Comment by dsihdekuhfhfgf** [comment]
> > did you find the answer cause i got the same problem
> 
> I got it working after delething the game file, the launcher and the yaagl os application support folder and reinstalling everything again

how did u do that??

**Comment by 3Shain** [comment]
https://github.com/3Shain/yet-another-anime-game-launcher/issues/225#issuecomment-1950793722
