### ISSUE TITLE
keep seeing fatal error when opening launcher

### ISSUE THREAD

**Issue by itami-afk** [3Shain/yet-another-anime-game-launcher#199]
whenever opening the launcher it shows this

<img width="705" alt="Screenshot 2023-10-06 at 4 35 27 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/147155057/3202c20f-9bf8-45b8-9e38-aecaee245841">

 - macOS: 13.5.2 Ventura
 - Device: Macbook air 
 - CPU: Apple M1
 - RAM: 8G 

i tried deleting every files i had related to yaagl and genshin and restarted but nothing seems to work..

**Comment by 3Shain** [comment]
https://github.com/3Shain/yet-another-anime-game-launcher/issues/225#issuecomment-1950793722
