### ISSUE TITLE
Game is crashing on dialog in Sumeru. macOS Sonoma 14.0

### ISSUE THREAD

**Issue by stefanlight8** [3Shain/yet-another-anime-game-launcher#200]
**The bug**
Game is crashing on dialog with Rana, forest ranger, from Sumeru after a fight with red energy (lmao i don't remember how it is name). On this moment i stuck in this dialog and cannot exit to other quests. There was also significant freezes and some visual bugs prior to the dialogue.

**Screenshots**
![Screenshot 2023-10-07 at 15 58 26](https://github.com/3Shain/yet-another-anime-game-launcher/assets/64615032/08d22e38-d0bd-4e4c-9a2d-23c2d707c72a)

**System Information**
 - macOS Sonoma 14.0
 - Mac Mini 2020
 - Apple M1
 - 16 GB

**Additional context**
I tried to use Metal hud, disable anychrous shader compiling. Nothing is helping.
I can't to downgrade on Ventura or Monterey.

**Logs**
[neutralinojs.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/12837852/neutralinojs.log)
[game_1696683538346.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/12837850/game_1696683538346.log)

(fun fact that a size of Yaagl OS folder in Application Support is diminished on over 700 megabytes)

**Comment by stefanlight8** [comment]
I recoded a video that demonstrate a crash of game at the end of dialog
![Video](https://github.com/3Shain/yet-another-anime-game-launcher/assets/64615032/7bb1d550-d4ff-4c3b-9066-7be7c0384459)

**Comment by MrJefferson99** [comment]
Ive also been having this problem and havent been able to solve it, have you been able to fix this issue yet?

**Comment by stefanlight8** [comment]
> Ive also been having the same type of problem with another cutscene and havent been able to solve it, have you been able to fix this issue yet?

same thing is happening with new event "The Poetry of Waters" in Li Yue. On second dialog 🙁
the first problem was fixed by disabling a patch, but this - no

**Comment by 51ug** [comment]
> > Ive also been having the same type of problem with another cutscene and havent been able to solve it, have you been able to fix this issue yet?
> 
> same thing is happening with new event "The Poetry of Waters" in Li Yue. On second dialog 🙁 the first problem was fixed by disabling a patch, but this - no

I am on MacOS Sonoma 14.0 and having the same exact crash with the new Liyue event. Also running into this issue early-ish in the Sumeru archon questline. I noticed I also crash very infrequently in certain character's burst animations. Maybe something related to voiced cutscenes? That's a common denominator at least for what I've experienced.

**Comment by ciciasmith** [comment]
I'm having the exact same problem. Lots of crashes in the new event, and in various story quests, always during voiced dialogue. If I experience a crash on one line of dialogue and reopen the game, it will always crash again at the exact same point again. I'm on Sonoma 14.0 as well.

**Comment by kiralotame** [comment]
Guys I managed to solve this problem just by choosing an older version of wine in launcher.

**Comment by 51ug** [comment]
> Guys I managed to solve this problem just by choosing an older version of wine in launcher.

That’s awesome. Could you share which version of Wine you switched to? I’ll verify that it fixes it on my machine too.

**Comment by 51ug** [comment]
> I'm having the exact same problem. Lots of crashes in the new event, and in various story quests, always during voiced dialogue. If I experience a crash on one line of dialogue and reopen the game, it will always crash again at the exact same point again. I'm on Sonoma 14.0 as well.

I want to clarify this issue and note that I also experienced a replicable crash (same point in dialog) during a world quest (unvoiced dialog).

Also as far as Wine distribution is concerned (see above comment) I experienced this issue on gi-wine-1.2.

**Comment by kiralotame** [comment]
So I changed to unstable-gi-wine-1.1.2 and after that I haven’t experienced any crashes in any dialogues.

**Comment by 51ug** [comment]
> So I changed to unstable-gi-wine-1.1.2 and after that I haven’t experienced any crashes in any dialogues.

Thank you for clarifying I’ll test this out later!

**Comment by ciciasmith** [comment]
Ah that seemed to work for me too! i'd started getting crashes while in combat as well, but i switched to gi-wine-1.0 and the problems have all disappeared
