### ISSUE TITLE
Error Code: 31-4302 YAAGI

### ISSUE THREAD

**Issue by HANKO1** [3Shain/yet-another-anime-game-launcher#202]
Launch genshin impact using yaagi, the game opens up, the door in the loading screen opens, I click on it and I get error code: 31-4302

 - macOS: [Sonoma 14.0]
 - Device: [MacBook Pro 13 inch 2022]
 - CPU: [Apple M2 Chip]
 - Dedicated GPU (if any): [e.g.  AMD Radeon Pro 5300M ]
 - RAM: [16GB]

**Comment by waterlens** [comment]
This is the same issue to #3

**Comment by Crimson521** [comment]
same error
what t0 do dont have much time
its been like this for 15 days

**Comment by levitabris** [comment]
Same here, it has been working quite well before a few days earlier.

My Spec:
macOS: [Sonoma 14.1.2]
Device: [MacBook Air 13 inch 2022]
CPU: [Apple M1 Chip]
RAM: [16GB]

**Comment by Sillygoat36** [comment]
did anyone find a fix????

**Comment by 3Shain** [comment]
https://github.com/3Shain/yet-another-anime-game-launcher/issues/255#issuecomment-1950778029
