### ISSUE TITLE
YAAGL 4.2.0, MAC M1, after install and downlaod, start option is not shown.

### ISSUE THREAD

**Issue by GoldRequiem64** [3Shain/yet-another-anime-game-launcher#207]
"launch game" option not shown after install and game file download.
- installed YAAGL  (4.2.0) and anime game on Mac silicon (ventura 13.4.1)
- install and game is using 92.78 GB on disk, launcher is still prompting "install game".

Is wine a prerequisite that needs to be installed beforehand?

**Comment by GoldRequiem64** [comment]
Deleted files and restarted download.

**Comment by kunthshah21** [comment]
did that solve? Because I believe Yaagl does not work on apple silicon right?
