### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by GAWNOED** [3Shain/yet-another-anime-game-launcher#210]
When i start installing the game, it gives an error

![image](https://github.com/3Shain/yet-another-anime-game-launcher/assets/150957044/04fcd866-eed4-448e-a42f-ea628f06a1f8)

 - macOS: [Sonoma 14.0]
 - Device: [iMac Retina 5K, 27-inch, 2020 ]
 - CPU: [3.1 GHz 6‑core Intel Core i5 processor ]
 - Dedicated GPU): [AMD Radeon Pro 5300 4 G ]
 - RAM: [8G ]

**Comment by Menelkir** [comment]
Where's your game directory? It seems you pointed to somewhere inside the Applications folder.
Try creating a folder in your home and install the game there instead.

**Comment by 3Shain** [comment]
https://github.com/3Shain/yet-another-anime-game-launcher/issues/225#issuecomment-1950793722
