### ISSUE TITLE
endless captcha

### ISSUE THREAD

**Issue by Uraoros08** [3Shain/yet-another-anime-game-launcher#217]
infinite captcha,infinite captcha white rectangle
- macOS: [for example, 14.1 . 1 sonoma] - Device: [for example, MacBookPro 16 inches 2019 ] - Processor: [for example, Apple M1, - RAM: [for example, 8G ] *

**Comment by 3Shain** [comment]
https://github.com/3Shain/yet-another-anime-game-launcher/issues/255#issuecomment-1950778029
