### ISSUE TITLE
error code 31-4302

### ISSUE THREAD

**Issue by Sillygoat36** [3Shain/yet-another-anime-game-launcher#222]
error code 31-4302 it says my game is not up to date, not sure what to do, I redownloaded the entire game and yaagl, lmk

**Screenshots**

 - macOS: [e.g. 13.1 Ventura]
 - Device: MacBook Pro 13 inch
 - CPU: Apple M1

**Comment by Sillygoat36** [comment]
macOs sonoma 14.2

**Comment by SuperGurl** [comment]
I have the same issue

- macOS: 12.4 Monterey
- Device: (Retina, 13-inch, 2019)
- Graphics: Intel
They said that YAAGL can support intel Macs!

**Comment by abdul-royyaq** [comment]
I also have the same problem, but I know the error is with the audio voice over which hasn't been installed, try to check `GenshinImpact_Data/StreamingAssets/AudioAssets` folder, do you already have a folder named `English(US)` `Japanese` or other?.
If isn't, you can download it directly, get the download link from the [official API](https://sdk-os-static.mihoyo.com/hk4e_global/mdk/launcher/api/resource?launcher_id=10&key=gcStgarh), you can use the find function in the browser, search for the keyword `Audio_` then download audio voiceover pack do you want and unarchived in the Genshin Impact installation folder.

**Comment by SuperGurl** [comment]
did it work for you?

**Comment by abdul-royyaq** [comment]
> did it work for you?

Yes, but that's not the cause of the problem, it's just a coincidence.
The real cause of the problem is the disable anticeat feature.

Go to Settings (gear logo) > Game > Turn off AC patch and checklist the disabled checkbox.
However, make sure you block logging and telemetry servers for security reasons.

```
# Genshin logging servers
overseauspider.yuanshen.com
osuspider.yuanshen.com
ys-log-upload-os.hoyoverse.com
```

**Comment by SuperGurl** [comment]
Settings? Like in the game launcher?

**Comment by 3Shain** [comment]
https://github.com/3Shain/yet-another-anime-game-launcher/issues/255#issuecomment-1950778029
