### ISSUE TITLE
Uncomplete Application

### ISSUE THREAD

**Issue by DragonDude20** [3Shain/yet-another-anime-game-launcher#223]
When I downloaded release 0.1.5, Yaagl.OS.app.tar.gz, I opened it as regular and instead got an application that when opened provided the notification along the lines of "Application cannot be opened because it is either incomplete or invalid." Something like that. So I downloaded 0.0.25, the version thatI saw Andrew Tsai use when I found about YAGGL. Please help me.

System Information:
 - macOS: 14.1.2 Sonoma
 - Device: MacbookPro 13inch 2018
 - CPU: 2.3 GHz Quad-Core Intel Core i5
 - Dedicated GPU (if any): None
 - RAM: 8GB

**Additional context**
I redownloaded twice, didn't help. I learned about YAAGL from Andrew Tsai's [video](https://www.youtube.com/watch?v=XplXeOdR98U), so now I'm using 0.0.25, which is what he used to play Genshin

**Comment by 3Shain** [comment]
There are tons of tutorials on how to solve "Application cannot be opened because it is either incomplete or invalid." on Google.
