### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by hammerman17** [3Shain/yet-another-anime-game-launcher#225]
Fatal error when trying to install game
Downloaded the launcher from github. When the pophub for the genshin launcher comes up it shows another message stating "fatal error". I've added the exact message below.

<img width="1284" alt="Screenshot 2023-12-19 at 10 23 13 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/154359256/29a80691-6092-4fe5-bbcf-0f0ad0dec054">

**System Information (please complete the following information):**
 - macOS: Ventura 13.5
 - Device: 15.6 inch M@ Macbook Air
 - CPU: Apple M2
 - RAM: 16 GB

**Comment by alextda617** [comment]
The new version 4.3 is now released so I guess we all just have to wait for another YAAGL version

**Comment by Twixxik** [comment]
Delele folder ~/Library/Application Support/Yaagl OS
And reopen launcher

**Comment by 3Shain** [comment]
> Delele folder ~/Library/Application Support/Yaagl OS And reopen launcher

This is the golden solution
