### ISSUE TITLE
Could you please the launcher to launch latest genshin impact for Mac m1 

### ISSUE THREAD

**Issue by karan68** [3Shain/yet-another-anime-game-launcher#233]
The feature is deployed for intel mac and not M1 , if you guys are ok I am a software developer from india , would love to contribute on the project, can we connect and discuss

**Comment by karan68** [comment]
any update on this?

**Comment by Menelkir** [comment]
Ask apple, it's a rosetta issue.
https://developer.apple.com/forums/thread/743838

**Comment by 3Shain** [comment]
fixed

**Comment by karan68** [comment]
how is this fixed , i don't see it fixed in my app @3Shain

**Comment by Menelkir** [comment]
Why don't you fork, make your modifications and create a PR then?

**Comment by karan68** [comment]
I was just asking as it was commented fixed and closed ,i thought i was missing something. Why so furious bro

**Comment by Menelkir** [comment]
Uh? Who is furious? I've just pointed out what everyone does (including myself) to propose a feature.
