### ISSUE TITLE
when GI games be released for ARM macO

### ISSUE THREAD

**Issue by ajsid09** [3Shain/yet-another-anime-game-launcher#236]
**Describe the bug**
when GI games be released for ARM macO

**Screenshots**

**System Information (please complete the following information):**
 - macOS: [e.g. 13.1 Ventura]
 - Device: [e.g. MacbookPro 16inch 2019 ]
 - CPU: [e.g. Apple M1, Intel i7 9750H ]
 - Dedicated GPU (if any): [e.g.  AMD Radeon Pro 5300M ]
 - RAM: [e.g. 16G ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Menelkir** [comment]
Ask apple, it's a rosetta issue.
https://developer.apple.com/forums/thread/743838

**Comment by Foul-Tarnished** [comment]
> Ask apple, it's a rosetta issue. https://developer.apple.com/forums/thread/743838

@3Shain 
https://feedbackassistant.apple.com/feedback/13503265
The issue doesn't exist anymore...

What did Apple replied ? Will it be fixed or not ?

**Comment by Foul-Tarnished** [comment]
> Ask apple, it's a rosetta issue. https://developer.apple.com/forums/thread/743838

I can't access the issue
https://feedbackassistant.apple.com/feedback/13503265

Any news ?

**Comment by waterlens** [comment]
> > Ask apple, it's a rosetta issue. https://developer.apple.com/forums/thread/743838
> 
> I can't access the issue https://feedbackassistant.apple.com/feedback/13503265
> 
> Any news from Apple ?

No. But I believe Apple has fixed the reported bug and we should wait for its update.

**Comment by Menelkir** [comment]
Some people on discord tested out, still borked.
