### ISSUE TITLE
crashes when reverting patches

### ISSUE THREAD

**Issue by dsihdekuhfhfgf** [3Shain/yet-another-anime-game-launcher#238]
I click launch the game and when reverting patches it crashes. how can I open the game?
iMac Apple M1
go wine 1.2
I tried to change it and reinstall the game but it didn't work out.

**Comment by akitort** [comment]
if u got any solutions then plzs do say

**Comment by Menelkir** [comment]
Ask apple, it's a rosetta issue.
https://developer.apple.com/forums/thread/743838
