### ISSUE TITLE
Game won't Launch/run

### ISSUE THREAD

**Issue by fashalul** [3Shain/yet-another-anime-game-launcher#245]
**Describe the bug**
just stuck on the launcher/running page and the game won't even load I INSTALLED AND DID EVERYTHING ALREADY but it just won't launch-

**Screenshots**
<img width="1279" alt="Screenshot 2024-01-10 at 12 09 42 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/155303601/e5cfbfca-27f0-4891-9fec-de8d417b83fc">
It just stuck like this- I let it load for A WHOLE DAY but the game won't launch/run-

**System Information (please complete the following information):**
 - macOS: version 14.1.1
 - Device: MacBook Pro 13-inch M2 2022
 - CPU: Apple M2
 - RAM: 8GB

**Additional context**
I've already done all the other steps this last step is what's the problem- it just wont launch/run- pls help😭

**Comment by Sillygoat36** [comment]
same lmk if you figure it out

**Comment by Menelkir** [comment]
It doesn't work on arm yet, it's written on the release page.
