### ISSUE TITLE
it says i need the latest game files?

### ISSUE THREAD

**Issue by 7onedout** [3Shain/yet-another-anime-game-launcher#246]
![Screenshot 2024-01-13 at 7 45 08 PM](https://github.com/3Shain/yet-another-anime-game-launcher/assets/156556249/33f769c9-cb76-4ac2-9ce9-54cf023e27cd)

**Comment by chiyouhen** [comment]
same issue

**Comment by chiyouhen** [comment]
I understand.

1. Launch game WITHOUT *Disable AC Patch* if you need login with captcha.
2. Once login has been done, launch game WITH *Disable AC Patch*, the game won't report error.

**Comment by 7onedout** [comment]
OH MY GOD THANK YOU SO MUCH I WAS MESSING WITH THE GAME FILES FOR A WEEK BLESS YOU OH MY
