### ISSUE TITLE
Command return non-zero code mv -f /Users/charles/Library/Application\ Support/Yaagl\ OS/wineprefix/drive_c/windows/system32/dxgi.dll /Users/charles/Library/Application\ Support/Yaagl\ OS/wineprefix/drive_c/windows/system32/dxgi.dll.bak

### ISSUE THREAD

**Issue by VDCharles** [3Shain/yet-another-anime-game-launcher#247]
Can anybody help on this issue? 
Command return non-zero code
mv -f /Users/charles/Library/Application\ Support/Yaagl\ OS/wineprefix/drive_c/windows/system32/dxgi.dll /Users/charles/Library/Application\ Support/Yaagl\ OS/wineprefix/drive_c/windows/system32/dxgi.dll.bak

**Comment by daviddg75** [comment]
i have the same probleme

**Comment by 3Shain** [comment]
remove the whole folder `/Users/<your username>/Library/Application\ Support/Yaagl\ OS/` (not just empty it. remove the folder)
