### ISSUE TITLE
login screen won't send verification code

### ISSUE THREAD

**Issue by valeriorussotto** [3Shain/yet-another-anime-game-launcher#252]
when you open the game, it will show as always the login screen, after putting in email and password it will ask to sent you a verification code but clicking on that button will only show a blank screen and nothing else.

 - macOS: [Sonoma 14.4]
 - Device: [e.g. MacbookPro 13inch M2 ]
 - CPU: Apple M2]
 - RAM: [8G ]

**Comment by 3Shain** [comment]
https://github.com/3Shain/yet-another-anime-game-launcher/issues/255#issuecomment-1950778029
