### ISSUE TITLE
 After the latest update dose not work on M2 Macbook air

### ISSUE THREAD

**Issue by AvgGymenjoyer** [3Shain/yet-another-anime-game-launcher#254]
when I launch the game it starts to load for a while and then goes back to launch the game. it dose not launch

**System Information 
 - macOS: [e.g. 14.3 Sonoma latest available update to normal people]
 - Device: [e.g. MacbookAir 13inch 2022 ]
 - CPU: [e.g. Apple M2]
 - Dedicated GPU (if any): [e.g.  M2 ]
 - RAM: [e.g. 8G ]
 
<img width="1280" alt="Screenshot 2024-02-02 at 7 35 46 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/158585233/3f41ae60-8a3a-45c1-a8a3-5aa79bc15482">
<img width="1278" alt="Screenshot 2024-02-02 at 7 36 01 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/158585233/f626d213-b99b-4efd-b814-151ca901f5be">

**Comment by mdosseva** [comment]
I'm getting the exact same issue. Also an M2, also updated to Sonoma.

**Comment by arsgaming1** [comment]
I'm having the same problem with Apple M1 MBA on 14.3 sonoma

**Comment by s4nflower** [comment]
rosetta bug.
Fixed with macos 14.4 beta 1

**Comment by AvgGymenjoyer** [comment]
> rosetta bug. Fixed with macos 14.4 beta 1

so do i have to wait for the sonoma 14.4 public release

**Comment by s4nflower** [comment]
> > rosetta bug. Fixed with macos 14.4 beta 1
> 
> so do i have to wait for the sonoma 14.4 public release

Well, no, you can update to developer beta, which is kinda junky, but I mean you at least will be able  to run the game

or yes, wait until 14.4

**Comment by akitort** [comment]
uhm will that work on m1 macbook air?

**Comment by mdosseva** [comment]
Is it possible for it to work with some earlier release of Sonoma? like 14.0? Or even 14.2?

**Comment by 3Shain** [comment]
sonoma 14.4 is required. no fixes for prior versions.
