### ISSUE TITLE
Data Error 

### ISSUE THREAD

**Issue by pmvrsi** [3Shain/yet-another-anime-game-launcher#259]
**Describe the bug**
Data Error, Full uninstall of the game is wanted

**Screenshots**
<img width="1680" alt="Screenshot 2024-02-09 at 8 20 18 am" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/121735202/005b89b6-06c0-4527-8613-306777e6b0d4">

**System Information (please complete the following information):**
 - macOS: [e.g. 14.4 Ventura Developer Beta]
 - Device: [e.g. MacbookPro 13inch 2020 ]
 - CPU: [e.g. Apple M2, Intel i7 9750H ]
 - RAM: [e.g. 8G ]

**Comment by tcripe4** [comment]
I am also getting this

**Comment by aazam476** [comment]
Turn off the AC patch within the YAAGL settings

**Comment by pmvrsi** [comment]
> Turn off the AC patch within the YAAGL settings

This worked!

**Comment by AnotiaWang** [comment]
> Turn off the AC patch within the YAAGL settings

Didn't work for me 🥲 macOS 14.4 Beta (23E5191e), Mainland China server
