### ISSUE TITLE
Error code: 31-4302, how do I fix it? 

### ISSUE THREAD

**Issue by bdshi99** [3Shain/yet-another-anime-game-launcher#262]
**Describe the bug**
I am able to launch and login to the game, but it shows that I need to download from official resource, anyone able to help? thanks. Also, will this affect the my account like being blocked as MIHOYO detect it as a hacker account?

**Screenshots**
<img width="1413" alt="Screenshot 2024-02-11 at 1 18 26 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/129980223/81d34f67-c0b0-4eb2-b9cc-6f177cff0ee7">

**System Information (please complete the following information):**
 - macOS: Sonoma beta 14.4
 -  Device: MBP m2 pro
 - CPU: M2 pro
 - RAM: 16gb

**Comment by greenbean1210** [comment]
I had the same issue. I solved the problem by enabling the 'Turn off the AC Patch' checkbox in the launcher settings.
<img width="1392" alt="스크린샷 2024-02-11 오후 10 24 26" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/76516426/c8d9e63b-334c-4d05-8f93-98e373bb6ced">

**Comment by hvdanyan** [comment]
> I had the same issue. I solved the problem by enabling the 'Turn off the AC Patch' checkbox in the launcher settings. <img alt="스크린샷 2024-02-11 오후 10 24 26" width="1392" src="https://private-user-images.githubusercontent.com/76516426/303921319-c8d9e63b-334c-4d05-8f93-98e373bb6ced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NjE4NTksIm5iZiI6MTcwNzY2MTU1OSwicGF0aCI6Ii83NjUxNjQyNi8zMDM5MjEzMTktYzhkOWU2M2ItMzM0Yy00ZDA1LThmOTMtOThlMzczYmI2Y2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE0MjU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNDVmYzUzNDI5MmU5ZGMyZDdkZmU2ZTc3MTI5ZjZjYTk4YWI2ZmNmYmEzM2ExNjRiYzNhOTc5ZWI0YjZjMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cEdtl-UgdCPwbBzUaU7IKiVCpunA2PglWdXJOxWMV8Q">

Yes! This indeed works.

**Comment by AikoMidori** [comment]
I would avoid disabling the ac patch since that increases your risk of getting banned 10 fold.

The cause of the issue has something to do with beta 2

**Comment by bdshi99** [comment]
> I had the same issue. I solved the problem by enabling the 'Turn off the AC Patch' checkbox in the launcher settings. <img alt="스크린샷 2024-02-11 오후 10 24 26" width="1392" src="https://private-user-images.githubusercontent.com/76516426/303921319-c8d9e63b-334c-4d05-8f93-98e373bb6ced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MDIyMzAsIm5iZiI6MTcwNzcwMTkzMCwicGF0aCI6Ii83NjUxNjQyNi8zMDM5MjEzMTktYzhkOWU2M2ItMzM0Yy00ZDA1LThmOTMtOThlMzczYmI2Y2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDAxMzg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNjQ5MDU5MTc2YTgwNDczYWVlZWMyMGIwMmM3YWMyNWY3NDNkY2MxMWY5ODM2NTUwYjNmZWU5ZGIyYjg1MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SsjB2D_J83oK5WlapsUezWUkSICChTaK8XwJL_9QwGk">

thanks bro!
