### ISSUE TITLE
Some problem with the patches

### ISSUE THREAD

**Issue by Sh1buraji** [3Shain/yet-another-anime-game-launcher#263]
When launching the game, the loading title suddenly changes to reverting patches and the game does not launch

<img width="1440" alt="SCR-20240211-pqdu" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/140177673/67464a20-4db6-4113-b66a-fbcae67cb8cc">

Macbook: m1 air
Os version: 14.3.1

**Comment by Ravenaige** [comment]
same issue here

M1 macbook pro mac os sonoma 14.3.1 

I tried crossover and yaagl, doesnt working ://

**Comment by Sh1buraji** [comment]
> same issue here
> 
> M1 macbook pro mac os sonoma 14.3.1
> 
> I tried pc version crossover and yaagl, doesnt working ://
> 
> so I downloaded two times 85gb :/ any advice or help pls :/

Well, what I think is that we probably need to download macOS 14.4(The beta version) to use yaagl as it is instructed to do so on the download page. But I don't want to use a bug filled version of macOS so I am currently just sideloading the game through playcover. Maybe give that a try!

**Comment by 3Shain** [comment]
Sonoma 14.4 is required (due to a rosetta bug fixed in this version
