### ISSUE TITLE
Stuck Allocating Files on Disk 

### ISSUE THREAD

**Issue by Lykt-hub** [3Shain/yet-another-anime-game-launcher#267]
**Describe the bug**
First time launching the game and it is stuck allocating files on disk.

**Screenshots**
<img width="1302" alt="Screenshot 2024-02-14 at 12 01 53 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/13710837/b93dc630-e80a-4ff2-a7e4-f23128a024d2">

**System Information (please complete the following information):**
 - macOS: 14.3.1 (23D60)
 - Device: MacBook Pro 14-inch, 2021
 - CPU: Apple M1 Pro
 - Dedicated GPU (if any): N/A
 - RAM: 16G

**Additional context**

**Logs (if any)**

**Comment by 3Shain** [comment]
reopen if it takes longer than 1 hr

**Comment by Lykt-hub** [comment]
@3Shain i let it run for 2 hours and nothing changed. still stuck on the allocating files on disk.
