### ISSUE TITLE
Trying to Build in M1 Mac

### ISSUE THREAD

**Issue by jonpol01** [3Shain/yet-another-anime-game-launcher#27]
had pnpm install as `arm64`

and at `pnpm start` . Got this error 

> neu: INFO Error: ENOENT: no such file or directory, chmod 'bin/neutralino-mac_arm64'

Can you follow up on how to build this custom neutralino.? So I can build this too on my M1.

**Comment by 3Shain** [comment]
You can get `neutralino-mac_arm64` in their latest release 4.11.0.

---

Sync your repo and now it should just work.

**Comment by jonpol01** [comment]
Hi, thanks for the followup.
Tried downloading and building that file. But whichever it is I am getting this error.
Not sure if this was neutralinojs issue or not.

![Screenshot 2023-04-02 at 17 55 25](https://user-images.githubusercontent.com/10163076/229342842-1067bff0-033c-44ca-aeda-da9fd27591ba.png)
