### ISSUE TITLE
help me T_T

### ISSUE THREAD

**Issue by akitort** [3Shain/yet-another-anime-game-launcher#279]
<img width="1440" alt="Screenshot 2024-03-10 at 11 59 29 AM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/142984210/14caf1d9-8e9c-445c-b81f-c613bc91b6c0">

**Comment by Somwow** [comment]
Fist log in with ac patch off: off verify then close application.
then open with ac patch off: on in game setting on launcher and enter the game.

**Comment by akitort** [comment]
thanx brotherrrrrr!!!!
