### ISSUE TITLE
PS4 Controller not working

### ISSUE THREAD

**Issue by Pogzhsd2** [3Shain/yet-another-anime-game-launcher#28]
**Describe the bug**
Controller doesent work with genshin.

**System Information (please complete the following information):**
 - macOS: [e.g. 13.2 Ventura]
 - Device: [Macbook Air 2020]
 - CPU: [Mac M1]
 - Dedicated GPU (if any): [None]
 - RAM: [8GB]

**Additional context**
what i saw was xbox buttons and not ps4 buttons, and controller doesent work.

**Logs (if any)**
If you tell me where it is, ill give it.

**Comment by Pogzhsd2** [comment]
[game_1680261029617.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11121320/game_1680261029617.log)

**Comment by mbs0ft** [comment]
Try to open launcher through Steam or launch Ryujinx and then Game launcher, I guess this happens because limited macOS controller support (?)

**Comment by Pogzhsd2** [comment]
The new update fixed it (0.0.37), But its registering like an xbox controller

**Comment by Pogzhsd2** [comment]
Ill make a new issue regarding this.
