### ISSUE TITLE
Graphical Glitch In-Game 

### ISSUE THREAD

**Issue by johancedaniel** [3Shain/yet-another-anime-game-launcher#29]
**Describe the bug**

Graphical glitches while in-game. Look at the screenshot for the issue.

**Screenshots**
<img width="1728" alt="Screenshot 2023-04-01 at 12 44 26 AM" src="https://user-images.githubusercontent.com/102495052/229210742-858d7719-fe2c-42ff-a546-aec12f3babf4.png">

**System Information (please complete the following information):**
 - macOS: 13.4 Ventura beta
 - Device: MacbookPro 16inch 2021 
 - CPU: Apple M1 Pro
 - RAM: 16 GB RAM

**Additional context**
I have used different wine versions on the app and tried the workaround 3 and turning of AC patch. The graphical issue still persists. The issue is same with the previous versions as well.

**Logs (if any)**

[game_1680289837424.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11125265/game_1680289837424.log)
<img width="1728" alt="Screenshot 2023-04-01 at 12 44 26 AM" src="https://user-images.githubusercontent.com/102495052/229211258-fd4b29f0-97ca-4a99-a358-1ee922615154.png">

**Comment by 3Shain** [comment]
Try to check integrity in launcher setting

**Comment by johancedaniel** [comment]
yes that fixes things
