### ISSUE TITLE
So I noticed if I sign in with the anticheat bypass on and then turn it off, the game still continues to work.

### ISSUE THREAD

**Issue by homurahomu1** [3Shain/yet-another-anime-game-launcher#34]
Is this intentional, or is the anticheat still being bypassed? I would like to know because I don't want my account to be banned.

**Comment by 3Shain** [comment]
The Anti-cheat driver __can not__ work on wine at all, and it's still not clear why user can still log in but anyway that's the current situation.

**Comment by homurahomu1** [comment]
Ah okay, so the "turn off the AC patch" toggle turns off the patch but the user can still sign in for some weird reason even though the patch is off and the anticheat is off?

thank you by the way

**Comment by 3Shain** [comment]
> Ah okay, so the "turn off the AC patch" toggle turns off the patch but the user can still sign in for some weird reason even though the patch is off and the anticheat is off?

true
