### ISSUE TITLE
error

### ISSUE THREAD

**Issue by L1vaa** [3Shain/yet-another-anime-game-launcher#35]
i get this error^ when select wine: gi-wine-1.0

Error: Command return non-zero code
mv -f /Users/lev/Anime\ game/UnityPlayer.dll.bak /Users/lev/Anime\ game/UnityPlayer.dll
StdOut:

StdErr:
mv: rename /Users/lev/Anime game/UnityPlayer.dll.bak to /Users/lev/Anime game/UnityPlayer.dll: No such file or directory

**System Information:**
 - macOS: [e.g. 13.3 Ventura]
 - Device: [e.g. Mac mini m1 ]
 - CPU: [e.g. Apple M1 ]
 - RAM: [e.g. 16G ]

**Comment by L1vaa** [comment]
![Снимок экрана 2023-04-01 в 22 19 42](https://user-images.githubusercontent.com/125485531/229310141-0f8141ae-91ff-43e7-b311-56a07263b57c.png)

**Comment by 3Shain** [comment]
Check integrity in launcher setting
