### ISSUE TITLE
M1 Build

### ISSUE THREAD

**Issue by jonpol01** [3Shain/yet-another-anime-game-launcher#38]
Hi, thanks for the followup.
Tried both downloading and building that file `neutralino-mac_arm64`. But whichever it is I am getting this error.
`neu: INFO Error: spawn Unknown system error -8`
Not sure if this was neutralinojs issue or not.

![Screenshot 2023-04-02 at 17 55 25](https://user-images.githubusercontent.com/10163076/229342842-1067bff0-033c-44ca-aeda-da9fd27591ba.png)

_Originally posted by @jonpol01 in https://github.com/3Shain/yet-another-anime-game-launcher/issues/27#issuecomment-1493270380_

**Comment by 3Shain** [comment]
Use another node version. You can install a `nvm` and try to use `v16` or `v14`
