### ISSUE TITLE
Stuck at the Game is Running

### ISSUE THREAD

**Issue by 00UNPRO00** [3Shain/yet-another-anime-game-launcher#39]
Issue
<img width="1470" alt="Screenshot 2023-04-02 at 17 34 02" src="https://user-images.githubusercontent.com/129649161/229344795-76904bf1-c3cc-409a-9019-40800c7ef9e6.png">

Launcher is stuck at the game is running but the data is being upload at Icloud Storage. Do I need to wait for the upload to complete?

**System Information (please complete the following information):**
 - macOS: [e.g. 13.3 Ventura]
 - Device: [e.g. Macbook Air M2 Chip ]
 - CPU: [e.g. Apple M2]

**Comment by 3Shain** [comment]
No, delete it. And don't select any path that will be synced by icloud.

**Comment by 00UNPRO00** [comment]
Also, the reason why it was stuck at "Game is Running DO NOT CLOSE THE
LAUNCHER" is because wine 1.0 is not working. I select 1.2 wine and it
works fine. As of now, I'm downloading 10GB resources again hahaha
