### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by L1vaa** [3Shain/yet-another-anime-game-launcher#40]
Game doesn't start

**Screenshots**
![Снимок экрана 2023-04-02 в 13 54 43](https://user-images.githubusercontent.com/125485531/229348503-accfb41e-d4cf-4c74-9ffe-9bde7eafb384.png)
![Снимок экрана 2023-04-02 в 13 56 56](https://user-images.githubusercontent.com/125485531/229348587-d6dbc13a-d346-450f-bc91-23230f1b3289.png)
![Снимок экрана 2023-04-02 в 13 57 18](https://user-images.githubusercontent.com/125485531/229348605-ecea7b9d-1978-4c30-a68c-b754e903f452.png)

**System Information (please complete the following information):**
 - macOS: [e.g. 13.3 Ventura]
 - Device: [e.g. Mac mini m1 ]
 - CPU: [e.g. Apple M1]
 - RAM: [e.g. 16G ]

**Comment by 3Shain** [comment]
Change `gi-wine-1.0` to `unstable-gi-wine-1.2`
