### ISSUE TITLE
Game crashes when running through YAAGL

### ISSUE THREAD

**Issue by devraza** [3Shain/yet-another-anime-game-launcher#401]
**Describe the bug**
If I launch the game through YAAGL (no matter what version of wine I use) it opens, but immediately crashes or otherwise gets stuck on the MiHoYo screen.

**System Information (please complete the following information):**
 - macOS: [14.5 Sonoma]
 - Device: [MacbookAir 2020 ]
 - CPU: [Apple M1]
 - RAM: [8G]

**Additional context**
The game *starts*, but either gets stuck on the 'MiHoYo' screen or just crashes after that. I can't seem to set the launcher to use CrossOver either, despite giving both programs full disk access and CrossOver being in `/Applications` - according to the FAQ, this should be because my system has only 8GB of RAM. However, if I run the executable file (YuanShen.exe) through CrossOver, it works fine.

**Comment by Sipperz** [comment]
Yes Crossover will not appear on 8GB RAM models, using "Unstable-bh-gptk-1.0" on 8GB Ram models is the best way to experience the game as of now, till DMXT gets implemented.
