### ISSUE TITLE
error

### ISSUE THREAD

**Issue by L1vaa** [3Shain/yet-another-anime-game-launcher#41]
Error: Command return non-zero code
mv -f /Users/lev/Library/Application\ Support/Yaagl\ OS/wineprefix/drive_c/windows/system32/dxgi.dll.bak /Users/lev/Library/Application\ Support/Yaagl\ OS/wineprefix/drive_c/windows/system32/dxgi.dll
StdOut:

StdErr:
mv: rename /Users/lev/Library/Application Support/Yaagl OS/wineprefix/drive_c/windows/system32/dxgi.dll.bak to /Users/lev/Library/Application Support/Yaagl OS/wineprefix/drive_c/windows/system32/dxgi.dll: No such file or directory

**Screenshots**
![Снимок экрана 2023-04-02 в 14 12 47](https://user-images.githubusercontent.com/125485531/229349276-1394102d-9aec-4a48-bb9a-2c701864325d.png)
![Снимок экрана 2023-04-02 в 14 14 42](https://user-images.githubusercontent.com/125485531/229349308-8eb3ca12-db28-42b5-9970-901486e15beb.png)

**System Information:**
 - macOS: [e.g. 13.3 Ventura]
 - Device: [e.g. Mac mini m1 ]
 - CPU: [e.g. Apple M1]
 - RAM: [e.g. 16G ]

**Comment by L1vaa** [comment]
the game itself has some bugs with the light
![Снимок экрана 2023-04-02 в 14 09 44](https://user-images.githubusercontent.com/125485531/229349356-f3de9b83-6f3f-4e4c-9c13-b9c2ac24edb0.png)
![Снимок экрана 2023-04-02 в 14 09 57](https://user-images.githubusercontent.com/125485531/229349361-963465f6-2372-48d3-92a5-0466bf0ae477.png)

**Comment by L1vaa** [comment]
> Error: Command return non-zero code mv -f /Users/lev/Library/Application\ Support/Yaagl\ OS/wineprefix/drive_c/windows/system32/dxgi.dll.bak /Users/lev/Library/Application\ Support/Yaagl\ OS/wineprefix/drive_c/windows/system32/dxgi.dll StdOut:
> 
> StdErr: mv: rename /Users/lev/Library/Application Support/Yaagl OS/wineprefix/drive_c/windows/system32/dxgi.dll.bak to /Users/lev/Library/Application Support/Yaagl OS/wineprefix/drive_c/windows/system32/dxgi.dll: No such file or directory
> 
> **Screenshots** ![Снимок экрана 2023-04-02 в 14 12 47](https://user-images.githubusercontent.com/125485531/229349276-1394102d-9aec-4a48-bb9a-2c701864325d.png) ![Снимок экрана 2023-04-02 в 14 14 42](https://user-images.githubusercontent.com/125485531/229349308-8eb3ca12-db28-42b5-9970-901486e15beb.png)
> 
> **System Information:**
> 
> * macOS: [e.g. 13.3 Ventura]
> * Device: [e.g. Mac mini m1 ]
> * CPU: [e.g. Apple M1]
> * RAM: [e.g. 16G ]

I forgot to mention that the error occurs after closing the game

**Comment by L1vaa** [comment]
I checked the integrity in the launcher settings

**Comment by 3Shain** [comment]
Why are there so many problems... Check integrity then restart your mac and try again. If that still doesn't solve your problem, uninstall Yaagl completely (but not the game) and then re-install (remember change wine to `unstable-gi-wine-1.2`).

**Comment by 3Shain** [comment]
Also, don't ** open a lot of issues. You can just __reopen__

**Comment by L1vaa** [comment]
> ~Also, don't ** open a lot of issues. You can just **reopen**~ nvm, just reply here if you get problems and I definitely can see it. So don't open another issue.

Thank you so much
