### ISSUE TITLE
I don't even know what to call this.

### ISSUE THREAD

**Issue by ac0608** [3Shain/yet-another-anime-game-launcher#46]
**Describe the bug**
..?

**Screenshots**
<img width="2226" alt="Screenshot 2023-04-02 at 21 39 58" src="https://user-images.githubusercontent.com/129690610/229377877-eff30b97-f6c1-4ed7-896a-0fa8a104803f.png">
<img width="2240" alt="Screenshot 2023-04-02 at 21 44 16" src="https://user-images.githubusercontent.com/129690610/229378047-825668a8-e565-43b3-87c1-bc4c1675a2fe.png">

**System Information (please complete the following information):**
 - macOS: 13.3 Ventura
 - Device: iMac 24inch 2021
 - CPU: Apple M1
 - Dedicated GPU (if any): none
 - RAM: 8GB

**Additional Context**
Uhh.. after i press to start the game, everything starts to spaz out and go blurry etc, fps drops.. idek, doesn't seem like a recommended way to play GI.

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by 3Shain** [comment]
DXVK is not working properly. Check file integrity in launcher settings and try again.

> doesn't seem like a recommended way to play GI.

Who did recommend? At least I didn't, and I won't based on the fact you get only 8G RAMs.

---

If problem still exists, just reply in this issue.

**Comment by ac0608** [comment]
> DXVK is not working properly. Check file integrity in launcher settings and try again.
> will do, will have to re-download it since it kept crashing.
> > doesn't seem like a recommended way to play GI.
> 
> Who did recommend? At least I didn't, and I won't based on the fact you get only 8G RAMs.
> bad wording, maybe not recommend, just gave good insights that it worked well.
> If problem still exists, just reply in this issue.
