### ISSUE TITLE
There isn't any audio although all settings are on and maxed out

### ISSUE THREAD

**Issue by ac0608** [3Shain/yet-another-anime-game-launcher#50]
**Describe the bug**
No audio

**Screenshots**
<img width="1597" alt="Screenshot 2023-04-03 at 01 01 34" src="https://user-images.githubusercontent.com/129690610/229386153-13d3dc1a-0104-4217-b14e-0ca9eaa6b338.png">

**System Information (please complete the following information):**
 - macOS: 13.3 Ventura
 - Device: iMac 24inch 2021
 - CPU: Apple M1
 - RAM: 8GB

**Comment by bose-pramuanpornsatid** [comment]
@ac0608 How were you able to solve the problem. I also don't have any audio output.
