### ISSUE TITLE
fail to load dll file when open the game.

### ISSUE THREAD

**Issue by chenpinetree** [3Shain/yet-another-anime-game-launcher#53]
**Describe the bug**
fail to load these 2 dll file when open the game.

**Screenshots**
<img width="344" alt="iShot_2023-04-03_14 28 14" src="https://user-images.githubusercontent.com/43738241/229429333-766596cd-38f6-4215-9ca1-0f0e410631d4.png">
<img width="337" alt="iShot_2023-04-03_14 28 20" src="https://user-images.githubusercontent.com/43738241/229429819-77282ad7-857e-4726-ae86-e1f675cc2a7a.png">

**System Information (please complete the following information):**
 - macOS: 13.3 Ventura
 - Device:  MacbookPro 16inch 
 - CPU: M1
 - Dedicated GPU (if any): 32 GPU
 - RAM: 32G

**Comment by 3Shain** [comment]
Use `gi-wine-1.2`.
