### ISSUE TITLE
Can I run Genshin Impact Cloud Game（Aka 云·原神）in wine

### ISSUE THREAD

**Issue by zhipu123** [3Shain/yet-another-anime-game-launcher#58]
**Is your feature request related to a problem? Please describe.**
原神占用太多硬盘空间了，能不能运行 云原神·windows版作为替代？
Genshin Impact takes up a lot of disk space, and I was wondering if it's possible to run Cloud Genshin·Windows version as an alternative?
**Describe the solution you'd like**
云原神·windows版 不支持运行在虚拟机中 [1](https://www.zhihu.com/question/581284431)
有没有什么办法能够绕过？
I understand that Cloud Genshin·Windows version does not support running in a virtual machine [1](https://www.zhihu.com/question/581284431). Are there any other workarounds to this issue?

**Comment by 3Shain** [comment]
我试过，不行。
