### ISSUE TITLE
数据异常

### ISSUE THREAD

**Issue by Softsister520** [3Shain/yet-another-anime-game-launcher#6]
设备型号：MacPro2019 (28核Intel Xeon 48GB内存 AMD Redeon Pro W6600X 8 GB)

系统版本：13.2 (22D49)

在游戏下载资源包后数据异常

**Comment by Softsister520** [comment]
Wine版本:gi-wine-1.0
DXVK HUD:不显示
DXVK Shader异步变异:启用
Retina模式:启用

**Comment by 3Shain** [comment]
duplicated #3
