### ISSUE TITLE
At least 108GiB (116.0GB) of freespace is required Message but I have 140GB free

### ISSUE THREAD

**Issue by AleTheTwin** [3Shain/yet-another-anime-game-launcher#60]
Just tried to install and this message show up

I tried deleting Application Support files and tried again, but message still pops

**System Information:**
 - macOS: Ventura 13.3
 - Device: Mac mini 2020
 - CPU: Apple M1
 - RAM: 8GB]

**Logs **
`
INFO 2023-04-05 19:17:27,560 Checking github endpoints api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:27,941 Using github proxy https://ghp.3shain.uk/ api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:27,942 echo $PPID api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:27,973 ./sidecar/aria2/aria2c -d / --no-conf --enable-rpc --rpc-listen-port=6868 --rpc-listen-all=true --rpc-allow-origin-all --input-file /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/aria2.session --save-session /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/aria2.session --pause true --stop-with-process 35018 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:27,987 35038 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:27,987 ./sidecar/aria2/aria2c -d / --no-conf --enable-rpc --rpc-listen-port=6868 --rpc-listen-all=true --rpc-allow-origin-all --input-file /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/aria2.session --save-session /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/aria2.session --pause true --stop-with-process 35018 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:40,510 killing process 35038 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:40,511 kill 35038 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:43,400 Checking github endpoints api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:43,727 Using github proxy https://ghp.3shain.uk/ api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:43,729 echo $PPID api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:43,753 ./sidecar/aria2/aria2c -d / --no-conf --enable-rpc --rpc-listen-port=6868 --rpc-listen-all=true --rpc-allow-origin-all --input-file /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/aria2.session --save-session /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/aria2.session --pause true --stop-with-process 35063 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:43,766 35077 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:43,767 ./sidecar/aria2/aria2c -d / --no-conf --enable-rpc --rpc-listen-port=6868 --rpc-listen-all=true --rpc-allow-origin-all --input-file /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/aria2.session --save-session /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/aria2.session --pause true --stop-with-process 35063 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:44,277 Launched aria2 version 1.35.0 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:44,555 rm -rf /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/wineprefix api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:59,108 rm -rf /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/wine api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:59,165 mkdir -p /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/wine api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:17:59,195 tar -zxvf /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/wine.tar.gz -C /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/wine api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:00,506 osascript -e do\ shell\ script\ \"xattr\ -r\ -d\ com.apple.quarantine\ /Users/alethetwin/Library/Application\\\\\ Support/Yaagl\\\\\ OS/wine\"\ with\ administrator\ privileges api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:04,406 WINEPREFIX=/Users/alethetwin/Library/Application\ Support/Yaagl\ OS/wineprefix /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/wine/bin/wine64 wineboot -u api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:27,362 WINEPREFIX=/Users/alethetwin/Library/Application\ Support/Yaagl\ OS/wineprefix /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/wine/bin/wine64 winecfg -v win10 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:36,852 killing process 35077 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:36,853 kill 35077 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:37,366 Checking github endpoints api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:37,718 Using github proxy https://ghp.3shain.uk/ api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:37,720 echo $PPID api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:37,744 ./sidecar/aria2/aria2c -d / --no-conf --enable-rpc --rpc-listen-port=6868 --rpc-listen-all=true --rpc-allow-origin-all --input-file /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/aria2.session --save-session /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/aria2.session --pause true --stop-with-process 35275 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:37,758 35290 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:37,758 ./sidecar/aria2/aria2c -d / --no-conf --enable-rpc --rpc-listen-port=6868 --rpc-listen-all=true --rpc-allow-origin-all --input-file /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/aria2.session --save-session /Users/alethetwin/Library/Application\ Support/Yaagl\ OS/aria2.session --pause true --stop-with-process 35275 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:38,264 Launched aria2 version 1.35.0 api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:38,269 {"architecture":"x64","frequency":2400000000,"logicalThreads":8,"model":"Apple M1","physicalCores":8,"physicalUnits":1,"vendor":""} api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:39,013 HOME:/Users/alethetwin api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:18:42,755 /bin/df -g /Users/alethetwin/Anime\ Game | /usr/bin/awk \{print\ \$4\} | /usr/bin/grep -v ^Available api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:19:16,414 /bin/df -g /Users/alethetwin/Anime\ Game | /usr/bin/awk \{print\ \$4\} | /usr/bin/grep -v ^Available api/debug/debug.cpp:17 alethetwin@unknown-host
INFO 2023-04-05 19:20:34,404 /bin/df -g /Users/alethetwin/Anime\ Game | /usr/bin/awk \{print\ \$4\} | /usr/bin/grep -v ^Available api/debug/debug.cpp:17 alethetwin@unknown-host`

**Comment by 3Shain** [comment]
`/bin/df -g /Users/alethetwin/Anime\ Game | /usr/bin/awk \{print\ \$4\} | /usr/bin/grep -v ^Available`  run in terminal and let me know what it outputs

**Comment by AleTheTwin** [comment]
it prints 87, do you know why in system settings it prints a higher value

**Comment by 3Shain** [comment]
You can learn more about `df` command and see where your free space goes. The command I provide you gives the free space __under certain path__ and the system setting (likely) gives you all utilisable free space on disk. They are not the same thing most of the time.

**Comment by AleTheTwin** [comment]
Well, thanks for the help
