### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by raghuramshankar** [3Shain/yet-another-anime-game-launcher#63]
**Describe the bug**
After downloading and installing game files, game won't launch beyond the main menu. 
Crashes in the loading menu.
Seems to be a missing dll file.

**Screenshots**
![image](https://user-images.githubusercontent.com/40054659/230496651-6c2360eb-2a5c-4345-9626-a7a3e106b9cc.png)

**System Information (please complete the following information):**
 - macOS: 13.3 Ventura
 - Device: Mac Mini 2023
 - CPU: Apple M2
 - Dedicated GPU (if any): No
 - RAM: 16GB

**Additional context**
Using gi-wine-1.2 and default settings

**Comment by raghuramshankar** [comment]
Seems like one of your scripts wants to rename `UnityPlayer.dll.bak` to `UnityPlayer.dll`. I tried to manually rename the existing `UnityPlayer.dll` to `UnityPlayer.dll.bak` and start the game but it still gives me the same error. Maybe its trying to do it twice and it can't find that file the second time?

**Comment by 3Shain** [comment]
Check integrity in launcher setting

**Comment by raghuramshankar** [comment]
Works fine now thanks for your work!
