### ISSUE TITLE
Game cannot run, Code-9006.

### ISSUE THREAD

**Issue by AaronComo** [3Shain/yet-another-anime-game-launcher#65]
- macOS: 13.1 Ventura
 - Device: MacbookAir
 - CPU: Apple M2

<img width="1470" alt="uTools_1681013106833" src="https://user-images.githubusercontent.com/107360494/230753854-c73a41fe-a912-45f1-bf60-960be06190d4.png">

I install this game on my portable hard disk. When I launched it, I got this message. However I can use my Windows devices to run it without '9006' problem.

I've tried shutting down the VPN and modifying the dns server, but still can't solve it.

**Comment by livcm** [comment]
the game should be installed on an APFS partition

**Comment by 3Shain** [comment]
Install on internal SSD or format your external drive APFS
