### ISSUE TITLE
ESC button will cause the game frozen completely

### ISSUE THREAD

**Issue by Rize-woomy** [3Shain/yet-another-anime-game-launcher#66]
My Device: MacBook Air M2 16G 1T
OS Version: macOS 13.3.1
Using the default setting, and once I press the ESC button, the game just completely freezes. This issue is not only appear when I try to reach the main menu, but it also gonna frozen the game in any menu once a press ESC, so it seems that ESC button will cause this issue somehow.

**Comment by 3Shain** [comment]
Try different wine versions.
