### ISSUE TITLE
Fatal Error opening Yaagl OS.app

### ISSUE THREAD

**Issue by jjarlego** [3Shain/yet-another-anime-game-launcher#68]
Device:

- macOS: [e.g. 12 Monterey]
- Device: [e.g. MacbookPro 14inch ]

Error Details:

Error: Command return non-zero code
mv -f /Users/*****/Anime\ Game\ YAAGL/UnityPlayer.dll.bak /Users/******/Anime\ Game\ YAAGL/UnityPlayer.dll
StdOut:

StdErr:
mv: rename /Users/*****/Anime Game YAAGL/UnityPlayer.dll.bak to /Users/*****/Anime Game YAAGL/UnityPlayer.dll: No such file or directory

**Comment by 3Shain** [comment]
Completely re-install Yaagl.

And from now on, don't close Yaagl if the progress bar is still presented (I know many users would like to close Yaagl as soon as game exits).
