### ISSUE TITLE
The launcher doesn't support version 3.6.0 currently, please wait for updates

### ISSUE THREAD

**Issue by erysmvn** [3Shain/yet-another-anime-game-launcher#70]
<img width="1440" alt="Schermata 2023-04-12 alle 1 32 18 PM" src="https://user-images.githubusercontent.com/124170570/231444938-22ce73b5-da1a-4d2e-863b-d2eadeed984c.png">

is this normal or maybe im the problem?

does it work on intel macbooks too right?

**Comment by MasqueradeX45** [comment]
> <img alt="Schermata 2023-04-12 alle 1 32 18 PM" width="1440" src="https://user-images.githubusercontent.com/124170570/231444938-22ce73b5-da1a-4d2e-863b-d2eadeed984c.png">
> 
> is this normal or maybe im the problem?
> 
> does it work on intel macbooks too right?

I have this issue as well, but I'm on an m1 MacBook. I think the launcher actually doesn't support 3.6.0 right now

**Comment by lavablelavs** [comment]
Same issue here

**Comment by 3Shain** [comment]
It literally told you to wait for updates.

**Comment by MasqueradeX45** [comment]
@3Shain Thank you for working on this project!
