### ISSUE TITLE
Not being able to update 

### ISSUE THREAD

**Issue by Crimson521** [3Shain/yet-another-anime-game-launcher#74]
I am not able to update genshin impact as it showed pre download I have already downloaded it but it shows on opening that new version of YAAGL in not updated please wait. for update . Help me solve this and if their are any steps to update the genshin please share it.
 - macOS: 13.2.1 Ventura
 - Device: MacbookAir 2 
 - CPU:  Apple M2
 - Dedicated GPU (if any): [e.g.  AMD Radeon Pro 5300M ]
 - RAM: 8G

**Comment by 3Shain** [comment]
#70
