### ISSUE TITLE
Seems like the advanced options is very difficult to enable  <- and that's intended

### ISSUE THREAD

**Issue by InfernalRabbit** [3Shain/yet-another-anime-game-launcher#78]
**Describe the bug**
I ve tried to enable FPS unloker - then i desribed that i need to click 6 times per second on version and nothing happend. Please provide more info or increase timelimit. If you are busy, i can make a PR for that

**System Information (please complete the following information):**
 - macOS: 13.1 Ventura
 - Device: MacbookPro 14inch 2021 ]
 - CPU: Apple M1
 - RAM: 16G

**Comment by 3Shain** [comment]
Did you compiled with `YAAGL_ADVANCED_ENABLE =1`?
