### ISSUE TITLE
hide the launcher after the game has started

### ISSUE THREAD

**Issue by jNaimXIII** [3Shain/yet-another-anime-game-launcher#79]
I just want to be able to close/hide the launcher while the game is running. Is it possible? Like, Discord and Spotify has the same behavior.

**Comment by 3Shain** [comment]
why?

**Comment by jNaimXIII** [comment]
Well, every other game launcher hides itself after the game launch so, maybe this one should do it as well?

**Comment by 3Shain** [comment]
The launcher is designed to revert the patch when game exits. 

And "XXX can do this way" is not a valid reason we must do so.
