### ISSUE TITLE
FPS Unlock Feature 

### ISSUE THREAD

**Issue by seathasky** [3Shain/yet-another-anime-game-launcher#8]
Would be nice of you could add the FPS unlocker to this. 60 fps is hurting my eyes on my high refresh rate monitor.

Thanks!

https://github.com/34736384/genshin-fps-unlock

**Comment by 3Shain** [comment]
implemented in https://github.com/3Shain/yet-another-anime-game-launcher/commit/bc91d90d0e89f408a7b28946668b45f06c3a4b64

**Comment by seathasky** [comment]
Ty for adding this. Respect!

**Comment by johancedaniel** [comment]
Hey in the game settings, i cant change the FPS settings in game to 120 fps, the max is 60fps, even though I have used the FPS unlocker
I have the 16inch M1 Pro

**Comment by seathasky** [comment]
Can your system reach high frames? What resolution are you running the game at?

I can easily maintain 120 at 1440p on Medium/High settings.
M2 Mac Mini Pro 12core cpu/19core gpu

![Screenshot 2023-04-01 at 2 39 31 AM](https://user-images.githubusercontent.com/17598024/229270166-f511aa8e-0467-48f5-a43f-6bbc3ff2bba1.png)

**Comment by johancedaniel** [comment]
no my system can reach 120 fps. my fps counter does reach 120 FPS, but the in-game settings on genshin impact only has the option of going to 60 fps

**Comment by seathasky** [comment]
> no my system can reach 120 fps. my fps counter does reach 120 FPS, but the in-game settings on genshin impact only has the option of going to 60 fps

The in game one is bypassed if you have the fps unlocked turned on, hence why I ask if you can reach 120. If the DXVK Hud is saying 120 in game, you are hitting 120.
