### ISSUE TITLE
Can not open successfully

### ISSUE THREAD

**Issue by giroro** [3Shain/yet-another-anime-game-launcher#83]
After I switch to retain mode and drag the window to the secondary screen, I can not open it.

Here is the log 

esync: up and running.
0110: thread_get_state failed on Apple Silicon - faking zero debug registers
0114: thread_get_state failed on Apple Silicon - faking zero debug registers
0128: thread_get_state failed on Apple Silicon - faking zero debug registers
012c: thread_get_state failed on Apple Silicon - faking zero debug registers
0130: thread_get_state failed on Apple Silicon - faking zero debug registers
0134: thread_get_state failed on Apple Silicon - faking zero debug registers
[2023-04-23 09:47:41.169] MultiThreadStackTrace init success!
GCGMAH active
01d8: thread_get_state failed on Apple Silicon - faking zero debug registers
017c: thread_get_state failed on Apple Silicon - faking zero debug registers
**** Crash! ****
0110: thread_get_state failed on Apple Silicon - faking zero debug registers
0114: thread_get_state failed on Apple Silicon - faking zero debug registers
012c: thread_get_state failed on Apple Silicon - faking zero debug registers
0130: thread_get_state failed on Apple Silicon - faking zero debug registers
0134: thread_get_state failed on Apple Silicon - faking zero debug registers
0138: thread_get_state failed on Apple Silicon - faking zero debug registers
013c: thread_get_state failed on Apple Silicon - faking zero debug registers
0140: thread_get_state failed on Apple Silicon - faking zero debug registers
0144: thread_get_state failed on Apple Silicon - faking zero debug registers
0148: thread_get_state failed on Apple Silicon - faking zero debug registers
014c: thread_get_state failed on Apple Silicon - faking zero debug registers
0150: thread_get_state failed on Apple Silicon - faking zero debug registers
0154: thread_get_state failed on Apple Silicon - faking zero debug registers
0158: thread_get_state failed on Apple Silicon - faking zero debug registers
015c: thread_get_state failed on Apple Silicon - faking zero debug registers
0164: thread_get_state failed on Apple Silicon - faking zero debug registers
0168: thread_get_state failed on Apple Silicon - faking zero debug registers
016c: thread_get_state failed on Apple Silicon - faking zero debug registers
0170: thread_get_state failed on Apple Silicon - faking zero debug registers
0174: thread_get_state failed on Apple Silicon - faking zero debug registers
0178: thread_get_state failed on Apple Silicon - faking zero debug registers
0180: thread_get_state failed on Apple Silicon - faking zero debug registers
0184: thread_get_state failed on Apple Silicon - faking zero debug registers
0188: thread_get_state failed on Apple Silicon - faking zero debug registers
018c: thread_get_state failed on Apple Silicon - faking zero debug registers
0190: thread_get_state failed on Apple Silicon - faking zero debug registers
0194: thread_get_state failed on Apple Silicon - faking zero debug registers
0198: thread_get_state failed on Apple Silicon - faking zero debug registers
019c: thread_get_state failed on Apple Silicon - faking zero debug registers
01a0: thread_get_state failed on Apple Silicon - faking zero debug registers
01a4: thread_get_state failed on Apple Silicon - faking zero debug registers
01a8: thread_get_state failed on Apple Silicon - faking zero debug registers
01ac: thread_get_state failed on Apple Silicon - faking zero debug registers
01b0: thread_get_state failed on Apple Silicon - faking zero debug registers
01b4: thread_get_state failed on Apple Silicon - faking zero debug registers
01b8: thread_get_state failed on Apple Silicon - faking zero debug registers
01bc: thread_get_state failed on Apple Silicon - faking zero debug registers
01c0: thread_get_state failed on Apple Silicon - faking zero debug registers
01c4: thread_get_state failed on Apple Silicon - faking zero debug registers
01c8: thread_get_state failed on Apple Silicon - faking zero debug registers
01cc: thread_get_state failed on Apple Silicon - faking zero debug registers
01d0: thread_get_state failed on Apple Silicon - faking zero debug registers
01d4: thread_get_state failed on Apple Silicon - faking zero debug registers
01d8: thread_get_state failed on Apple Silicon - faking zero debug registers
0190: thread_get_state failed on Apple Silicon - faking zero debug registers
762.080:0190:err:seh:call_stack_handlers invalid frame 00000000003026C0 (0000000019F22000-000000001A020000)
762.081:0190:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.

**Comment by 3Shain** [comment]
looks not good, try more times with different settings. also if you can find the crash log please post it here or email me (search for a file named `output_log.txt` and at the file location you will see a folder called `Crashes`. Send both of them to me)

**Comment by giroro** [comment]
你好：


我搜索不到&nbsp;&nbsp;output_log.txt


另外之前因为无法启动，我把环境改成了wine1.2，刚刚又重装了一遍，还是无法启动。
然后我又尝试把环境改回wine1.0，这回正常打开了。


总之非常感谢您开发这个工具








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "3Shain/yet-another-anime-game-launcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月23日(星期天) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [3Shain/yet-another-anime-game-launcher] Can not open successfully (Issue #83)





 
looks not good, try more times with different settings. also if you can find the crash log please post it here or email me (search for a file named output_log.txt and at the file location you will see a folder called Crashes. Send both of them to me)
