### ISSUE TITLE
Hang after running for a short while

### ISSUE THREAD

**Issue by acumon** [3Shain/yet-another-anime-game-launcher#85]
**Describe the bug**
It's installed successfully without any issue. and I can login successfully. But after a short while (< 5min), It hangs indefinitely without any other symptoms. CPU usage of the wine processes are high and constant

**Screenshots**
<img width="975" alt="image" src="https://user-images.githubusercontent.com/534201/234436314-5c4e819a-7a81-41fa-b9a3-1bd1b1a169be.png">

**System Information (please complete the following information):**
 - macOS: 13.3.1 (22E261)
 - Device: MacbookPro 16inch 2023
 - CPU: Apple M2 Pro
 - Dedicated GPU (if any): N/A
 - RAM: 32GB

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upluploadoad `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory
The logs often ends with these lines
```
0224: thread_get_state failed on Apple Silicon - faking zero debug registers
052c: thread_get_state failed on Apple Silicon - faking zero debug registers
0538: thread_get_state failed on Apple Silicon - faking zero debug registers
0540: thread_get_state failed on Apple Silicon - faking zero debug registers
024c: thread_get_state failed on Apple Silicon - faking zero debug registers
015c: thread_get_state failed on Apple Silicon - faking zero debug registers
037c: thread_get_state failed on Apple Silicon - faking zero debug registers
0380: thread_get_state failed on Apple Silicon - faking zero debug registers
0190: thread_get_state failed on Apple Silicon - faking zero debug registers
0194: thread_get_state failed on Apple Silicon - faking zero debug registers
0198: thread_get_state failed on Apple Silicon - faking zero debug registers
019c: thread_get_state failed on Apple Silicon - faking zero debug registers
01a0: thread_get_state failed on Apple Silicon - faking zero debug registers
01a4: thread_get_state failed on Apple Silicon - faking zero debug registers
0aac: thread_get_state failed on Apple Silicon - faking zero debug registers
01a8: thread_get_state failed on Apple Silicon - faking zero debug registers
01ac: thread_get_state failed on Apple Silicon - faking zero debug registers
0ac8: thread_get_state failed on Apple Silicon - faking zero debug registers
05d0: thread_get_state failed on Apple Silicon - faking zero debug registers
```

**Comment by Ahmed-Farook** [comment]
Which version of wine are you using?

**Comment by acumon** [comment]
The latest Yaagl release. if that's what you're asking

**Comment by 7Eterius** [comment]
Seems like i am having the same issue, mostly freezes during cutscenes or when the cutscene is loading.
