### ISSUE TITLE
FPS LOCKED ISSUES

### ISSUE THREAD

**Issue by AnonyKVB** [3Shain/yet-another-anime-game-launcher#89]
A while ago there was an option to change how much FPS you want to unlock in the Yaagl OS menu, and at that time I set my fps at 120fps and now a few update on the launcher later, for me there is no longer an option to change the FPS thing in the menu of the launcher and whenever I launch the game and play, the game will try to go pass 60fps and try to reach 120 fps but i want it deadlock on 60fps but I don't have the option to change anymore.

**System Information (please complete the following information):**
 - macOS: [e.g. 13.1 Ventura]
 - Device: [e.g. MacbookPro 13inch 2020 ]
 - CPU: [e.g. Apple M1, ]
 - RAM: [e.g. 8GB ]

**Comment by 3Shain** [comment]
delete `~/Library/Application Support/Yaagl OS/.storage/config_fpsunlock.neustorage` (noted `.storage` is hidden)
