### ISSUE TITLE
Giving Error:{"code":"NE_FS_FILRDER" "message": "Unable to open file: /Users/hii.xxiv/Library/Application Support/Yaag| OS/pkg_version"}

### ISSUE THREAD

**Issue by go-go24** [3Shain/yet-another-anime-game-launcher#92]
After downloading Yaagl again, it goes straight to the launcher and it gives this error:

<img width="458" alt="Screenshot 2023-05-06 at 1 36 29 PM" src="https://user-images.githubusercontent.com/130853343/236611933-aa1a7095-6a38-4f95-bb5d-43d3a9fbc60a.png">

System Information
 - macOS: 13.3.1 Ventura
 - Device: MacbookPro 13inch 2017
 - CPU: 2.3 GHz Dual-Core Intel Core i5 
 - RAM:  8GB

**Additional context**
I downloaded Yaagl once before but on starting the game, it would get stuck and restart the whole computer. At the moment, I am trying to download it while using my monitor and not my Macbook

Thank you very much

**Comment by 3Shain** [comment]
Delete `/Users/hii.xxiv/Library/Application Support/Yaagl OS` (the folder as a whole)

**Comment by go-go24** [comment]
I tried this but it seems like I don't have Yaagl OS under the Application Support file... What do I do?

**Comment by 3Shain** [comment]
No it must be here. There might be multiple `Application Support`, make sure you find the correct one (I've even provided you the absolute path, how can you not find it?)

**Comment by AKSHITXSHARMA** [comment]
I bud im also getting the same error so can u plzz tell me how to fix it  here do I need to past this /Users/hii.xxiv/Library/Application Support/Yaagl OS ??.
