### ISSUE TITLE
Everytime I try to download a language pack, the game crashes

### ISSUE THREAD

**Issue by MinminKeiw** [3Shain/yet-another-anime-game-launcher#94]
When I try to download a language pack, it starts the download for a few seconds and then instantly quits the game. I've tried downloading all the language audios, but it does the same thing to all of them.

 - macOS: 13.3.1 Ventura
 - Device: iMac 2019
 - CPU: 3 GHz 6-Core Intel Core i5
 - Dedicated GPU (if any): Radeon Pro 560X 4 GB
 - RAM: 250.69 GB

**Logs (if any)**

[game_1682691225064.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11411994/game_1682691225064.log)

**Comment by AnonyKVB** [comment]
bro got 250gb of ram 💀

**Comment by 3Shain** [comment]
Duplicated #57

**Comment by qiqiven** [comment]
When I try to download a language pack, it starts the download for a few seconds and then instantly quits the game.

macOS: 13.4.1 Ventura
Device: MacBook Air
RAM: 494.38 GB
Logs (if any)

log : driverError 6.24.07 AM.log
