### ISSUE TITLE
Error message when trying to launch

### ISSUE THREAD

**Issue by maxman1m** [3Shain/yet-another-anime-game-launcher#96]
**Describe the bug**
Game crashes every time, few seconds after launch and pops up with the error message mentioned below. I have tried multiple different wines and still the same, I also had issue with the game freezing during story quest prior to this.

![Screenshot 2023-05-08 at 1 01 52 am](https://user-images.githubusercontent.com/104472571/236685530-f057f633-fcc0-4f90-94f8-6d8b62eb967d.png)

**System Information (please complete the following information):**
 - macOS: 13.3.1 Ventura
 - Device: MacBook Pro 14-inch 2023
 - CPU: Apple M2 Pro
 - RAM: 16gb

**Additional context**
As I said earlier I had multiple issue with game freezing up when I tried to enter story quest so I hopped between wines and they might work for a day or couple of days and then start bugging out/crashing. Now I'm just getting that error message. Let me know if you need any logs or further information.

Cheers 😁

**Comment by 3Shain** [comment]
No solutions other than choosing different wine version (and it might not work)
