### ISSUE TITLE
Game sizing resolution

### ISSUE THREAD

**Issue by Dawson-dev127** [3Shain/yet-another-anime-game-launcher#98]
**Describe the bug**
When I try to run the game normally, It will be full screen but the resolution seems to be weird (first picture). But when I open the game with retina mode enabled the emulator, it wont be viewed at full screen (second Picture). Is there a way to fix it or is it just a bug?

**Screenshots**

![IMG_9231-min](https://github.com/3Shain/yet-another-anime-game-launcher/assets/83668490/bf6e7269-a7d2-4987-8393-1602221afe32)
![IMG_9232-min](https://github.com/3Shain/yet-another-anime-game-launcher/assets/83668490/fd14dbbf-4f71-4e2d-9d2b-50cf3b8022e4)

**System Information (please complete the following information):**
 - macOS: [13.3.1 Ventura]
 - Device: [Macbook Air M1 ]
 - CPU: [Apple M1 8-Core CPU]
 - Dedicated GPU (if any): [Apple (7-Core)]
 - RAM: [ 8GB ]

**Comment by 3Shain** [comment]
it will go normal after several launches (and don't change retina setting too often
