### ISSUE TITLE
random crash when I try to play

### ISSUE THREAD

**Issue by badtoke1** [3Shain/yet-another-anime-game-launcher#99]
the game loads up to the point when I press "start" and it gives me the loading screen with all the elements. when they all fill in signifying that the game is loaded, it takes me back to the launcher. I am not entirely sure what the whole "wine" thing is, but it is set to "gi-wine-1.0". Let me know if you need more information, Thank you.

 - macOS: version 11.6 Big Sur
 - Device: MacBook Air 13.3 Inch
 - CPU: Apple M1
 - RAM: 8G

**Comment by 3Shain** [comment]
try `gi-wine-1.2`

**Comment by badtoke1** [comment]
hmm it didn't work. I still crash after the loading screen. would another wine version work? should I try all of them?

**Comment by 3Shain** [comment]
you can try but I'm not sure any will work. it's not something definitely solvable (at least on my side).
